#ifndef _ANIM_H_
#define _ANIM_H_

enum anim_t {
	ANIM_LEFT_RIGHT,
	ANIM_LEFT_RIGHT_FLOOR,
	ANIM_UP_DOWN,
	ANIM_GRAVITY,
	ANIM_STATIC,
	ANIM_JEAN,
	ANIM_JUMP,
	ANIM_CYCLE_TILE,
	ANIM_CHASE,
	MAX_ANIMATORS
};

enum jane_anim_state_t {
	JANE_STATE_LEFT,
	JANE_STATE_LEFT_JUMP,
	JANE_STATE_LEFT_CROUCH,
	JANE_STATE_RIGHT,
	JANE_STATE_RIGHT_JUMP,
	JANE_STATE_RIGHT_CROUCH,
	JANE_STATE_DEATH,
};

enum obj_state {
	STATE_IDLE,
	STATE_MOVING_LEFT,
	STATE_MOVING_RIGHT,
	STATE_MOVING_DOWN,
	STATE_MOVING_UP,
	STATE_HOPPING_RIGHT,
	STATE_JUMPING,
	STATE_CROUCHING,
	STATE_FALLING,
	STATE_OFF_SCREEN,
	STATE_OFF_SCREEN_DELAY_1S,
	STATE_OFF_SCREEN_DELAY_2S,
};

extern struct animator animators[MAX_ANIMATORS];

void add_animator(struct displ_object *dpo, enum anim_t animidx);

#endif
