#include "banks.h"

#pragma DATA_PAGE 9

// PAGE_DYNTILES
#include "gen/rope.h"
#include "gen/hearth.h"
#include "gen/cross_status.h"
#include "gen/priest.h"
#include "gen/retro_logo.h"
#include "gen/satan.h"
#include "gen/cup.h"
#include "gen/splash.h"
#include "gen/trapdoor.h"
#include "gen/archer_skeleton.h"
#include "gen/crosswitch.h"
#include "gen/portal.h"
#include "gen/spear.h"
#include "gen/bell.h"
#include "gen/scroll.h"
#include "gen/red_scroll.h"
#include "gen/invisible_trigger.h"
#include "gen/cross.h"
#include "gen/gargolyne.h"
#include "gen/invertedcross.h"
#include "gen/lava.h"
#include "gen/toggle.h"
#include "gen/door.h"
#include "gen/plant.h"
#include "gen/hearth_status.h"
#include "gen/water.h"
#include "gen/dragon.h"
#include "gen/checkpoint.h"
#include "gen/stainedglass.h"
#include "gen/cross_small.h"
#include "gen/flame.h"
#include "gen/boss_explosion.h"
