#pragma DATA_PAGE 21

#include "gen/map1.h"
#include "gen/map2.h"
#include "gen/map3.h"
#include "gen/map4.h"
#include "gen/map5.h"
#include "gen/map6.h"
#include "gen/map7.h"
#include "gen/map8.h"
#include "gen/map9.h"
#include "gen/map10.h"
#include "gen/map11.h"
#include "gen/map12.h"
#include "gen/map13.h"
#include "gen/map14.h"
#include "gen/map15.h"
#include "gen/map16.h"
#include "gen/map17.h"
#include "gen/map18.h"
#include "gen/map19.h"
#include "gen/map20.h"
#include "gen/map21.h"
#include "gen/map22.h"
#include "gen/map23.h"

#include "gen/debug.h"
