// PAGE_MAPTILES
#include "gen/maptiles1.h"
#include "gen/maptiles2.h"
#include "gen/maptiles3.h"
#include "gen/maptiles3b.h"
#include "gen/maptiles4.h"
#include "gen/maptiles5.h"
#include "gen/maptiles6.h"
#include "gen/maptiles7.h"
