include ../build.mk
include $(SETUP_BUILD)

LOCAL_RES_DIR := ./res
include $(BUILD_RESOURCES)

LOCAL_ROM_NAME := rom256_test
LOCAL_SRC_FILES := rom256_test.c swap.c swap0.c
include $(BUILD_ROM_ASCII8)
