#ifndef _ANIM_H_
#define _ANIM_H_

enum anim_t {
  ANIM_GRAVITY,
  ANIM_STATIC,
  ANIM_JEAN,
  ANIM_JUMP,
  ANIM_CYCLE_TILE,
  ANIM_CHASE_FOREST,
  ANIM_CHASE_GRAVEYARD,
  ANIM_CLOSE_DOOR,
  ANIM_SHOOTER_PLANT,
  ANIM_FALLING_BULLETS,
  ANIM_WATERDROP,
  ANIM_FISH_JUMP,
  ANIM_SPLASH,
  ANIM_GHOST,
  ANIM_UP_DOWN_BOUNDED,
  ANIM_ARCHER_SKELETON,
  ANIM_HORIZONTAL_PROJECTILE,
  ANIM_GARGOLYNE,
  ANIM_INTRO_CHASE,
  ANIM_INTRO_JEAN,
  ANIM_LEFT_RIGHT_BOUNDED,
  ANIM_DEATH,
  ANIM_SCYTHE,
  ANIM_SATAN,
  ANIM_SATAN_BULLETS,
  ANIM_DRAGON_FLAME,
  ANIM_DRAGON_BULLETS,
  ANIM_HANGING_PRIEST,
  ANIM_EXPLOSION,
  ANIM_RED_PARCHMENT,
  ANIM_EVIL_CHAMBER,
  ANIM_JEAN_BONFIRE,
  ANIM_BLOCK_CROSSES,
  ANIM_CROSS,
  ANIM_TEMPLAR_BONFIRE,
  ANIM_LAVA,
  ANIM_WATER,
  ANIM_OPEN_DOOR,
  ANIM_CLOSE_DOOR_SATAN,
  MAX_ANIMATORS
};

enum jane_anim_state_t {
  JANE_STATE_LEFT,
  JANE_STATE_LEFT_JUMP,
  JANE_STATE_LEFT_CROUCH,
  JANE_STATE_RIGHT,
  JANE_STATE_RIGHT_JUMP,
  JANE_STATE_RIGHT_CROUCH,
  JANE_STATE_DEATH,
};

enum obj_state {
  STATE_IDLE,
  STATE_MOVING_LEFT,
  STATE_MOVING_RIGHT,
  STATE_MOVING_DOWN,
  STATE_MOVING_UP,
  STATE_HOPPING_RIGHT, // 5
  STATE_FALLING_RIGHT,
  STATE_JUMPING,
  STATE_CROUCHING,
  STATE_FALLING, // 9
  STATE_COLLISION,
  STATE_DEATH,
  STATE_OFF_SCREEN,
  STATE_OFF_SCREEN_DELAY_1S,
  STATE_OFF_SCREEN_DELAY_2S,
  STATE_OFF_SCREEN_DELAY_3S
};

extern Animator animators[MAX_ANIMATORS];

void add_animator(DisplayObject *dpo, enum anim_t animidx);

#endif
