#pragma DATA_PAGE 15

#include "gen/title_abandoned_church.h"
#include "gen/title_ashes_to_ashes.h"
#include "gen/title_banquet_of_death.h"
#include "gen/title_catacombs.h"
#include "gen/title_cave_of_illusions.h"
#include "gen/title_death_is_close.h"
#include "gen/title_escape.h"
#include "gen/title_evil_church.h"
#include "gen/title_gloomy_tunnels.h"
#include "gen/title_hangman_tree.h"
#include "gen/title_hidden_garden.h"
#include "gen/title_lake_of_despair.h"
#include "gen/title_pestilent_beast.h"
#include "gen/title_plagued_ruins.h"
#include "gen/title_prayerofhope.h"
#include "gen/title_the_altar.h"
#include "gen/title_tortured_souls.h"
#include "gen/title_tower_of_the_bell.h"
#include "gen/title_underground_river.h"
#include "gen/title_unexpected_gate.h"
#include "gen/title_wheel_of_faith.h"
#include "gen/title_wine_supplies.h"
