//
// Register Declarations for Microchip 16LF1904 Processor
//
//
// This header file was automatically generated by:
//
//	inc2h.pl V4850
//
//	Copyright (c) 2002, Kevin L. Pauba, All Rights Reserved
//
//	SDCC is licensed under the GNU Public license (GPL) v2.  Note that
//	this license covers the code to the compiler and other executables,
//	but explicitly does not cover any code or objects generated by sdcc.
//	We have not yet decided on a license for the run time libraries, but
//	it will not put any requirements on code linked against it. See:
// 
//	http://www.gnu.org/copyleft/gpl/html
//
//	See http://sdcc.sourceforge.net/ for the latest information on sdcc.
//
// 
#ifndef P16LF1904_H
#define P16LF1904_H

//
// Register addresses.
//
#define INDF0_ADDR	0x0000
#define INDF1_ADDR	0x0001
#define PCL_ADDR	0x0002
#define STATUS_ADDR	0x0003
#define FSR0_ADDR	0x0004
#define FSR0L_ADDR	0x0004
#define FSR0H_ADDR	0x0005
#define FSR1_ADDR	0x0006
#define FSR1L_ADDR	0x0006
#define FSR1H_ADDR	0x0007
#define BSR_ADDR	0x0008
#define WREG_ADDR	0x0009
#define PCLATH_ADDR	0x000A
#define INTCON_ADDR	0x000B
#define PORTA_ADDR	0x000C
#define PORTB_ADDR	0x000D
#define PORTC_ADDR	0x000E
#define PORTD_ADDR	0x000F
#define PORTE_ADDR	0x0010
#define PIR1_ADDR	0x0011
#define PIR2_ADDR	0x0012
#define TMR0_ADDR	0x0015
#define TMR1_ADDR	0x0016
#define TMR1L_ADDR	0x0016
#define TMR1H_ADDR	0x0017
#define T1CON_ADDR	0x0018
#define T1GCON_ADDR	0x0019
#define TRISA_ADDR	0x008C
#define TRISB_ADDR	0x008D
#define TRISC_ADDR	0x008E
#define TRISD_ADDR	0x008F
#define TRISE_ADDR	0x0090
#define PIE1_ADDR	0x0091
#define PIE2_ADDR	0x0092
#define OPTION_REG_ADDR	0x0095
#define PCON_ADDR	0x0096
#define WDTCON_ADDR	0x0097
#define OSCCON_ADDR	0x0099
#define OSCSTAT_ADDR	0x009A
#define ADRES_ADDR	0x009B
#define ADRESL_ADDR	0x009B
#define ADRESH_ADDR	0x009C
#define ADCON0_ADDR	0x009D
#define ADCON1_ADDR	0x009E
#define LATA_ADDR	0x010C
#define LATB_ADDR	0x010D
#define LATC_ADDR	0x010E
#define LATD_ADDR	0x010F
#define LATE_ADDR	0x0110
#define BORCON_ADDR	0x0116
#define FVRCON_ADDR	0x0117
#define ANSELA_ADDR	0x018C
#define ANSELB_ADDR	0x018D
#define ANSELE_ADDR	0x0190
#define PMADR_ADDR	0x0191
#define PMADRL_ADDR	0x0191
#define PMADRH_ADDR	0x0192
#define PMDAT_ADDR	0x0193
#define PMDATL_ADDR	0x0193
#define PMDATH_ADDR	0x0194
#define PMCON1_ADDR	0x0195
#define PMCON2_ADDR	0x0196
#define RC1REG_ADDR	0x0199
#define RCREG_ADDR	0x0199
#define RCREG1_ADDR	0x0199
#define TX1REG_ADDR	0x019A
#define TXREG_ADDR	0x019A
#define TXREG1_ADDR	0x019A
#define SP1BRGL_ADDR	0x019B
#define SPBRG_ADDR	0x019B
#define SPBRGL_ADDR	0x019B
#define SPBRGL1_ADDR	0x019B
#define SP1BRGH_ADDR	0x019C
#define SPBRGH_ADDR	0x019C
#define SPBRGH1_ADDR	0x019C
#define RC1STA_ADDR	0x019D
#define RCSTA_ADDR	0x019D
#define RCSTA1_ADDR	0x019D
#define TX1STA_ADDR	0x019E
#define TXSTA_ADDR	0x019E
#define TXSTA1_ADDR	0x019E
#define BAUD1CON_ADDR	0x019F
#define BAUDCON_ADDR	0x019F
#define BAUDCON1_ADDR	0x019F
#define WPUB_ADDR	0x020D
#define WPUE_ADDR	0x0210
#define IOCBP_ADDR	0x0394
#define IOCBN_ADDR	0x0395
#define IOCBF_ADDR	0x0396
#define LCDCON_ADDR	0x0791
#define LCDPS_ADDR	0x0792
#define LCDREF_ADDR	0x0793
#define LCDCST_ADDR	0x0794
#define LCDRL_ADDR	0x0795
#define LCDSE0_ADDR	0x0798
#define LCDSE1_ADDR	0x0799
#define LCDSE2_ADDR	0x079A
#define LCDDATA0_ADDR	0x07A0
#define LCDDATA1_ADDR	0x07A1
#define LCDDATA2_ADDR	0x07A2
#define LCDDATA3_ADDR	0x07A3
#define LCDDATA4_ADDR	0x07A4
#define LCDDATA5_ADDR	0x07A5
#define LCDDATA6_ADDR	0x07A6
#define LCDDATA7_ADDR	0x07A7
#define LCDDATA8_ADDR	0x07A8
#define LCDDATA9_ADDR	0x07A9
#define LCDDATA10_ADDR	0x07AA
#define LCDDATA11_ADDR	0x07AB
#define LCDDATA12_ADDR	0x07AC
#define LCDDATA15_ADDR	0x07AF
#define LCDDATA18_ADDR	0x07B2
#define LCDDATA21_ADDR	0x07B5
#define STATUS_SHAD_ADDR	0x0FE4
#define WREG_SHAD_ADDR	0x0FE5
#define BSR_SHAD_ADDR	0x0FE6
#define PCLATH_SHAD_ADDR	0x0FE7
#define FSR0L_SHAD_ADDR	0x0FE8
#define FSR0H_SHAD_ADDR	0x0FE9
#define FSR1L_SHAD_ADDR	0x0FEA
#define FSR1H_SHAD_ADDR	0x0FEB
#define STKPTR_ADDR	0x0FED
#define TOSL_ADDR	0x0FEE
#define TOSH_ADDR	0x0FEF

//
// Memory organization.
//



//         LIST

//==========================================================================
//  MPASM PIC16LF1904 processor include
// 
//  (c) Copyright 1999-2011 Microchip Technology, All rights reserved
//==========================================================================

//         NOLIST

//==========================================================================
//  This header file defines configurations, registers, and other useful
//  bits of information for the PIC16LF1904 microcontroller.  These names
//  are taken to match the data sheets as closely as possible.
//
//  Note that the processor must be selected before this file is included.
//  The processor may be selected the following ways:
//
//       1. Command line switch:
//               C:\MPASM MYFILE.ASM /PIC16LF1904
//       2. LIST directive in the source file
//               LIST   P=PIC16LF1904
//       3. Processor Type entry in the MPASM full-screen interface
//       4. Setting the processor in the MPLAB Project Dialog
//==========================================================================

//==========================================================================
//
//       Verify Processor
//
//==========================================================================
//        IFNDEF __16LF1904
//            MESSG "Processor-header file mismatch.  Verify selected processor."
//         ENDIF



//==========================================================================
//
//       Register Definitions
//
//==========================================================================

#define W                    0x0000
#define F                    0x0001

//----- Register Files -----------------------------------------------------

//-----Bank0------------------
extern __sfr  __at (INDF0_ADDR)                   INDF0;
extern __sfr  __at (INDF1_ADDR)                   INDF1;
extern __sfr  __at (PCL_ADDR)                     PCL;
extern __sfr  __at (STATUS_ADDR)                  STATUS;
extern __sfr  __at (FSR0_ADDR)                    FSR0;
extern __sfr  __at (FSR0L_ADDR)                   FSR0L;
extern __sfr  __at (FSR0H_ADDR)                   FSR0H;
extern __sfr  __at (FSR1_ADDR)                    FSR1;
extern __sfr  __at (FSR1L_ADDR)                   FSR1L;
extern __sfr  __at (FSR1H_ADDR)                   FSR1H;
extern __sfr  __at (BSR_ADDR)                     BSR;
extern __sfr  __at (WREG_ADDR)                    WREG;
extern __sfr  __at (PCLATH_ADDR)                  PCLATH;
extern __sfr  __at (INTCON_ADDR)                  INTCON;
extern __sfr  __at (PORTA_ADDR)                   PORTA;
extern __sfr  __at (PORTB_ADDR)                   PORTB;
extern __sfr  __at (PORTC_ADDR)                   PORTC;
extern __sfr  __at (PORTD_ADDR)                   PORTD;
extern __sfr  __at (PORTE_ADDR)                   PORTE;
extern __sfr  __at (PIR1_ADDR)                    PIR1;
extern __sfr  __at (PIR2_ADDR)                    PIR2;
extern __sfr  __at (TMR0_ADDR)                    TMR0;
extern __sfr  __at (TMR1_ADDR)                    TMR1;
extern __sfr  __at (TMR1L_ADDR)                   TMR1L;
extern __sfr  __at (TMR1H_ADDR)                   TMR1H;
extern __sfr  __at (T1CON_ADDR)                   T1CON;
extern __sfr  __at (T1GCON_ADDR)                  T1GCON;

//-----Bank1------------------
extern __sfr  __at (TRISA_ADDR)                   TRISA;
extern __sfr  __at (TRISB_ADDR)                   TRISB;
extern __sfr  __at (TRISC_ADDR)                   TRISC;
extern __sfr  __at (TRISD_ADDR)                   TRISD;
extern __sfr  __at (TRISE_ADDR)                   TRISE;
extern __sfr  __at (PIE1_ADDR)                    PIE1;
extern __sfr  __at (PIE2_ADDR)                    PIE2;
extern __sfr  __at (OPTION_REG_ADDR)              OPTION_REG;
extern __sfr  __at (PCON_ADDR)                    PCON;
extern __sfr  __at (WDTCON_ADDR)                  WDTCON;
extern __sfr  __at (OSCCON_ADDR)                  OSCCON;
extern __sfr  __at (OSCSTAT_ADDR)                 OSCSTAT;
extern __sfr  __at (ADRES_ADDR)                   ADRES;
extern __sfr  __at (ADRESL_ADDR)                  ADRESL;
extern __sfr  __at (ADRESH_ADDR)                  ADRESH;
extern __sfr  __at (ADCON0_ADDR)                  ADCON0;
extern __sfr  __at (ADCON1_ADDR)                  ADCON1;

//-----Bank2------------------
extern __sfr  __at (LATA_ADDR)                    LATA;
extern __sfr  __at (LATB_ADDR)                    LATB;
extern __sfr  __at (LATC_ADDR)                    LATC;
extern __sfr  __at (LATD_ADDR)                    LATD;
extern __sfr  __at (LATE_ADDR)                    LATE;
extern __sfr  __at (BORCON_ADDR)                  BORCON;
extern __sfr  __at (FVRCON_ADDR)                  FVRCON;

//-----Bank3------------------
extern __sfr  __at (ANSELA_ADDR)                  ANSELA;
extern __sfr  __at (ANSELB_ADDR)                  ANSELB;
extern __sfr  __at (ANSELE_ADDR)                  ANSELE;
extern __sfr  __at (PMADR_ADDR)                   PMADR;
extern __sfr  __at (PMADRL_ADDR)                  PMADRL;
extern __sfr  __at (PMADRH_ADDR)                  PMADRH;
extern __sfr  __at (PMDAT_ADDR)                   PMDAT;
extern __sfr  __at (PMDATL_ADDR)                  PMDATL;
extern __sfr  __at (PMDATH_ADDR)                  PMDATH;
extern __sfr  __at (PMCON1_ADDR)                  PMCON1;
extern __sfr  __at (PMCON2_ADDR)                  PMCON2;
extern __sfr  __at (RC1REG_ADDR)                  RC1REG;
extern __sfr  __at (RCREG_ADDR)                   RCREG;
extern __sfr  __at (RCREG1_ADDR)                  RCREG1;
extern __sfr  __at (TX1REG_ADDR)                  TX1REG;
extern __sfr  __at (TXREG_ADDR)                   TXREG;
extern __sfr  __at (TXREG1_ADDR)                  TXREG1;
extern __sfr  __at (SP1BRGL_ADDR)                 SP1BRGL;
extern __sfr  __at (SPBRG_ADDR)                   SPBRG;
extern __sfr  __at (SPBRGL_ADDR)                  SPBRGL;
extern __sfr  __at (SPBRGL1_ADDR)                 SPBRGL1;
extern __sfr  __at (SP1BRGH_ADDR)                 SP1BRGH;
extern __sfr  __at (SPBRGH_ADDR)                  SPBRGH;
extern __sfr  __at (SPBRGH1_ADDR)                 SPBRGH1;
extern __sfr  __at (RC1STA_ADDR)                  RC1STA;
extern __sfr  __at (RCSTA_ADDR)                   RCSTA;
extern __sfr  __at (RCSTA1_ADDR)                  RCSTA1;
extern __sfr  __at (TX1STA_ADDR)                  TX1STA;
extern __sfr  __at (TXSTA_ADDR)                   TXSTA;
extern __sfr  __at (TXSTA1_ADDR)                  TXSTA1;
extern __sfr  __at (BAUD1CON_ADDR)                BAUD1CON;
extern __sfr  __at (BAUDCON_ADDR)                 BAUDCON;
extern __sfr  __at (BAUDCON1_ADDR)                BAUDCON1;

//-----Bank4------------------
extern __sfr  __at (WPUB_ADDR)                    WPUB;
extern __sfr  __at (WPUE_ADDR)                    WPUE;

//-----Bank7------------------
extern __sfr  __at (IOCBP_ADDR)                   IOCBP;
extern __sfr  __at (IOCBN_ADDR)                   IOCBN;
extern __sfr  __at (IOCBF_ADDR)                   IOCBF;

//-----Bank15------------------
extern __sfr  __at (LCDCON_ADDR)                  LCDCON;
extern __sfr  __at (LCDPS_ADDR)                   LCDPS;
extern __sfr  __at (LCDREF_ADDR)                  LCDREF;
extern __sfr  __at (LCDCST_ADDR)                  LCDCST;
extern __sfr  __at (LCDRL_ADDR)                   LCDRL;
extern __sfr  __at (LCDSE0_ADDR)                  LCDSE0;
extern __sfr  __at (LCDSE1_ADDR)                  LCDSE1;
extern __sfr  __at (LCDSE2_ADDR)                  LCDSE2;
extern __sfr  __at (LCDSE2_ADDR)                  LCDSE2;
extern __sfr  __at (LCDDATA0_ADDR)                LCDDATA0;
extern __sfr  __at (LCDDATA1_ADDR)                LCDDATA1;
extern __sfr  __at (LCDDATA2_ADDR)                LCDDATA2;
extern __sfr  __at (LCDDATA3_ADDR)                LCDDATA3;
extern __sfr  __at (LCDDATA4_ADDR)                LCDDATA4;
extern __sfr  __at (LCDDATA5_ADDR)                LCDDATA5;
extern __sfr  __at (LCDDATA6_ADDR)                LCDDATA6;
extern __sfr  __at (LCDDATA7_ADDR)                LCDDATA7;
extern __sfr  __at (LCDDATA8_ADDR)                LCDDATA8;
extern __sfr  __at (LCDDATA9_ADDR)                LCDDATA9;
extern __sfr  __at (LCDDATA10_ADDR)               LCDDATA10;
extern __sfr  __at (LCDDATA11_ADDR)               LCDDATA11;
extern __sfr  __at (LCDDATA12_ADDR)               LCDDATA12;
extern __sfr  __at (LCDDATA15_ADDR)               LCDDATA15;
extern __sfr  __at (LCDDATA18_ADDR)               LCDDATA18;
extern __sfr  __at (LCDDATA21_ADDR)               LCDDATA21;

//-----Bank31------------------
extern __sfr  __at (STATUS_SHAD_ADDR)             STATUS_SHAD;
extern __sfr  __at (WREG_SHAD_ADDR)               WREG_SHAD;
extern __sfr  __at (BSR_SHAD_ADDR)                BSR_SHAD;
extern __sfr  __at (PCLATH_SHAD_ADDR)             PCLATH_SHAD;
extern __sfr  __at (FSR0L_SHAD_ADDR)              FSR0L_SHAD;
extern __sfr  __at (FSR0H_SHAD_ADDR)              FSR0H_SHAD;
extern __sfr  __at (FSR1L_SHAD_ADDR)              FSR1L_SHAD;
extern __sfr  __at (FSR1H_SHAD_ADDR)              FSR1H_SHAD;
extern __sfr  __at (STKPTR_ADDR)                  STKPTR;
extern __sfr  __at (TOSL_ADDR)                    TOSL;
extern __sfr  __at (TOSH_ADDR)                    TOSH;

//----- STATUS Bits -----------------------------------------------------


//----- BSR Bits -----------------------------------------------------



//----- INTCON Bits -----------------------------------------------------



//----- PORTA Bits -----------------------------------------------------


//----- PORTB Bits -----------------------------------------------------


//----- PORTC Bits -----------------------------------------------------


//----- PORTD Bits -----------------------------------------------------


//----- PORTE Bits -----------------------------------------------------


//----- PIR1 Bits -----------------------------------------------------


//----- PIR2 Bits -----------------------------------------------------


//----- T1CON Bits -----------------------------------------------------



//----- T1GCON Bits -----------------------------------------------------



//----- TRISA Bits -----------------------------------------------------


//----- TRISB Bits -----------------------------------------------------


//----- TRISC Bits -----------------------------------------------------


//----- TRISD Bits -----------------------------------------------------


//----- TRISE Bits -----------------------------------------------------


//----- PIE1 Bits -----------------------------------------------------


//----- PIE2 Bits -----------------------------------------------------


//----- OPTION_REG Bits -----------------------------------------------------



//----- PCON Bits -----------------------------------------------------


//----- WDTCON Bits -----------------------------------------------------



//----- OSCCON Bits -----------------------------------------------------



//----- OSCSTAT Bits -----------------------------------------------------


//----- ADCON0 Bits -----------------------------------------------------





//----- ADCON1 Bits -----------------------------------------------------



//----- LATA Bits -----------------------------------------------------


//----- LATB Bits -----------------------------------------------------


//----- LATC Bits -----------------------------------------------------


//----- LATD Bits -----------------------------------------------------


//----- LATE Bits -----------------------------------------------------


//----- BORCON Bits -----------------------------------------------------


//----- FVRCON Bits -----------------------------------------------------



//----- ANSELA Bits -----------------------------------------------------



//----- ANSELB Bits -----------------------------------------------------



//----- ANSELE Bits -----------------------------------------------------


//----- PMCON1 Bits -----------------------------------------------------


//----- SP1BRGL Bits -----------------------------------------------------


//----- SPBRG Bits -----------------------------------------------------


//----- SPBRGL Bits -----------------------------------------------------


//----- SPBRGL1 Bits -----------------------------------------------------


//----- SP1BRGH Bits -----------------------------------------------------


//----- SPBRGH Bits -----------------------------------------------------


//----- SPBRGH1 Bits -----------------------------------------------------


//----- RC1STA Bits -----------------------------------------------------


//----- RCSTA Bits -----------------------------------------------------


//----- RCSTA1 Bits -----------------------------------------------------


//----- TX1STA Bits -----------------------------------------------------


//----- TXSTA Bits -----------------------------------------------------


//----- TXSTA1 Bits -----------------------------------------------------


//----- BAUD1CON Bits -----------------------------------------------------


//----- BAUDCON Bits -----------------------------------------------------


//----- BAUDCON1 Bits -----------------------------------------------------


//----- WPUB Bits -----------------------------------------------------



//----- WPUE Bits -----------------------------------------------------


//----- IOCBP Bits -----------------------------------------------------



//----- IOCBN Bits -----------------------------------------------------



//----- IOCBF Bits -----------------------------------------------------



//----- LCDCON Bits -----------------------------------------------------



//----- LCDPS Bits -----------------------------------------------------



//----- LCDREF Bits -----------------------------------------------------


//----- LCDCST Bits -----------------------------------------------------



//----- LCDRL Bits -----------------------------------------------------



//----- LCDSE0 Bits -----------------------------------------------------


//----- LCDSE1 Bits -----------------------------------------------------


//----- LCDSE2 Bits -----------------------------------------------------


//----- LCDSE3 Bits -----------------------------------------------------


//----- LCDDATA0 Bits -----------------------------------------------------


//----- LCDDATA1 Bits -----------------------------------------------------


//----- LCDDATA2 Bits -----------------------------------------------------


//----- LCDDATA3 Bits -----------------------------------------------------


//----- LCDDATA4 Bits -----------------------------------------------------


//----- LCDDATA5 Bits -----------------------------------------------------


//----- LCDDATA6 Bits -----------------------------------------------------


//----- LCDDATA7 Bits -----------------------------------------------------


//----- LCDDATA8 Bits -----------------------------------------------------


//----- LCDDATA9 Bits -----------------------------------------------------


//----- LCDDATA10 Bits -----------------------------------------------------


//----- LCDDATA11 Bits -----------------------------------------------------


//----- LCDDATA12 Bits -----------------------------------------------------


//----- LCDDATA15 Bits -----------------------------------------------------


//----- LCDDATA18 Bits -----------------------------------------------------


//----- LCDDATA21 Bits -----------------------------------------------------


//----- STATUS_SHAD Bits -----------------------------------------------------



//==========================================================================
//
//       RAM Definitions
//
//==========================================================================
//        __MAXRAM  H'0FFF'
//        __BADRAM  H'0013'-H'0014'
//        __BADRAM  H'001A'-H'001E'
//        __BADRAM  H'001F'
//        __BADRAM  H'0093'-H'0094'
//        __BADRAM  H'0098'
//        __BADRAM  H'009F'
//        __BADRAM  H'0111'-H'0115'
//        __BADRAM  H'0118'-H'011F'
//        __BADRAM  H'018E'-H'018F'
//        __BADRAM  H'0197'-H'0198'
//        __BADRAM  H'01A0'-H'01EF'
//        __BADRAM  H'020C'
//        __BADRAM  H'020E'-H'020F'
//        __BADRAM  H'0211'-H'021F'
//        __BADRAM  H'0220'-H'026F'
//        __BADRAM  H'028C'-H'029F'
//        __BADRAM  H'02A0'-H'02EF'
//        __BADRAM  H'030C'-H'031F'
//        __BADRAM  H'0320'-H'036F'
//        __BADRAM  H'038C'-H'0393'
//        __BADRAM  H'0397'-H'039F'
//        __BADRAM  H'03A0'-H'03EF'
//        __BADRAM  H'040C'-H'0419'
//        __BADRAM  H'041A'-H'041F'
//        __BADRAM  H'0420'-H'046F'
//        __BADRAM  H'048C'-H'049F'
//        __BADRAM  H'04A0'-H'04EF'
//        __BADRAM  H'050C'-H'051F'
//        __BADRAM  H'0520'-H'056F'
//        __BADRAM  H'058C'-H'059F'
//        __BADRAM  H'05A0'-H'05EF'
//        __BADRAM  H'060C'-H'061F'
//        __BADRAM  H'0620'-H'066F'
//        __BADRAM  H'068C'-H'069F'
//        __BADRAM  H'06A0'-H'06EF'
//        __BADRAM  H'070C'-H'071F'
//        __BADRAM  H'0720'-H'076F'
//        __BADRAM  H'078C'-H'0790'
//        __BADRAM  H'0796'-H'0797'
//        __BADRAM  H'079C'-H'079F'
//        __BADRAM  H'07AD'-H'07AE'
//        __BADRAM  H'07B0'-H'07B1'
//        __BADRAM  H'07B3'-H'07B4'
//        __BADRAM  H'07B6'-H'07EF'
//        __BADRAM  H'080C'-H'081F'
//        __BADRAM  H'0820'-H'086F'
//        __BADRAM  H'088C'-H'089F'
//        __BADRAM  H'08A0'-H'08EF'
//        __BADRAM  H'090C'-H'091F'
//        __BADRAM  H'0920'-H'096F'
//        __BADRAM  H'098C'-H'099F'
//        __BADRAM  H'09A0'-H'09EF'
//        __BADRAM  H'0A0C'-H'0A1F'
//        __BADRAM  H'0A20'-H'0A6F'
//        __BADRAM  H'0A8C'-H'0A9F'
//        __BADRAM  H'0AA0'-H'0AEF'
//        __BADRAM  H'0B0C'-H'0B1F'
//        __BADRAM  H'0B20'-H'0B6F'
//        __BADRAM  H'0B8C'-H'0B9F'
//        __BADRAM  H'0BA0'-H'0BEF'
//        __BADRAM  H'0C0C'-H'0C1F'
//        __BADRAM  H'0C20'-H'0C6F'
//        __BADRAM  H'0C8C'-H'0C9F'
//        __BADRAM  H'0CA0'-H'0CEF'
//        __BADRAM  H'0D0C'-H'0D1F'
//        __BADRAM  H'0D20'-H'0D6F'
//        __BADRAM  H'0D8C'-H'0D9F'
//        __BADRAM  H'0DA0'-H'0DEF'
//        __BADRAM  H'0E0C'-H'0E1F'
//        __BADRAM  H'0E20'-H'0E6F'
//        __BADRAM  H'0E8C'-H'0E9F'
//        __BADRAM  H'0EA0'-H'0EEF'
//        __BADRAM  H'0F0C'-H'0F1F'
//        __BADRAM  H'0F20'-H'0F6F'
//        __BADRAM  H'0F8C'-H'0FE3'
//        __BADRAM  H'0FEC'

//==========================================================================
//
//       Configuration Bits
//
//   NAME            Address
//   CONFIG1           8007h
//   CONFIG2           8008h
//
//==========================================================================

// The following is an assignment of address values for all of the
// configuration registers for the purpose of table reads
#define _CONFIG1             0x8007
#define _CONFIG2             0x8008

//----- CONFIG1 Options --------------------------------------------------
#define _FOSC_INTOSC         0xFFFC    // INTOSC oscillator: I/O function on CLKIN pin
#define _FOSC_ECL            0xFFFD    // ECL, External Clock, Low Power Mode (0-0.5 MHz): device clock supplied to CLKIN pin
#define _FOSC_ECM            0xFFFE    // ECM, External Clock, Medium Power Mode (0.5-4 MHz): device clock supplied to CLKIN pin
#define _FOSC_ECH            0xFFFF    // ECH, External Clock, High Power Mode (4-32 MHz): device clock supplied to CLKIN pin

#define _WDTE_OFF            0xFFE7    // WDT disabled
#define _WDTE_SWDTEN         0xFFEF    // WDT controlled by the SWDTEN bit in the WDTCON register
#define _WDTE_NSLEEP         0xFFF7    // WDT enabled while running and disabled in Sleep
#define _WDTE_ON             0xFFFF    // WDT enabled

#define _PWRTE_ON            0xFFDF    // PWRT enabled
#define _PWRTE_OFF           0xFFFF    // PWRT disabled

#define _MCLRE_OFF           0xFFBF    // MCLR/VPP pin function is digital input
#define _MCLRE_ON            0xFFFF    // MCLR/VPP pin function is MCLR

#define _CP_ON               0xFF7F    // Program memory code protection is enabled
#define _CP_OFF              0xFFFF    // Program memory code protection is disabled

#define _BOREN_OFF           0xF9FF    // Brown-out Reset disabled
#define _BOREN_SBODEN        0xFBFF    // Brown-out Reset controlled by the SBOREN bit in the BORCON register
#define _BOREN_NSLEEP        0xFDFF    // Brown-out Reset enabled while running and disabled in Sleep
#define _BOREN_ON            0xFFFF    // Brown-out Reset enabled

#define _CLKOUTEN_ON         0xF7FF    // CLKOUT function is enabled on the CLKOUT pin
#define _CLKOUTEN_OFF        0xFFFF    // CLKOUT function is disabled. I/O or oscillator function on the CLKOUT pin

//----- CONFIG2 Options --------------------------------------------------
#define _WRT_ALL             0xFFFC    // 000h to 7FFh write protected, no addresses may be modified by PMCON control
#define _WRT_HALF            0xFFFD    // 000h to 3FFh write protected, 400h to 7FFh may be modified by PMCON control
#define _WRT_BOOT            0xFFFE    // 000h to 1FFh write protected, 200h to 7FFh may be modified by PMCON control
#define _WRT_OFF             0xFFFF    // Write protection off

#define _STVREN_OFF          0xFDFF    // Stack Overflow or Underflow will not cause a Reset
#define _STVREN_ON           0xFFFF    // Stack Overflow or Underflow will cause a Reset

#define _BORV_HI             0xFBFF    // Brown-out Reset Voltage (VBOR) set to 2.7V
#define _BORV_LO             0xFFFF    // Brown-out Reset Voltage (VBOR) set to 1.9V
#define _BORV_19             0xFFFF    // Brown-out Reset Voltage (VBOR) set to 1.9V

#define _LPBOR_ON            0xF7FF    // Low-Power BOR is enabled
#define _LPBOR_OFF           0xFFFF    // Low-Power BOR is disabled

#define _LVP_OFF             0xDFFF    // High-voltage on MCLR/VPP must be used for programming
#define _LVP_ON              0xFFFF    // Low-voltage programming enabled

//----- DEVID Equates --------------------------------------------------
#define _DEVID1              0x8006

//----- IDLOC Equates --------------------------------------------------
#define _IDLOC0              0x8000
#define _IDLOC1              0x8001
#define _IDLOC2              0x8002
#define _IDLOC3              0x8003

//         LIST

// ----- ADCON0 bits --------------------
typedef union {
  struct {
    unsigned char ADON:1;
    unsigned char GO_NOT_DONE:1;
    unsigned char CHS0:1;
    unsigned char CHS1:1;
    unsigned char CHS2:1;
    unsigned char CHS3:1;
    unsigned char CHS4:1;
    unsigned char :1;
  };
  struct {
    unsigned char :1;
    unsigned char ADGO:1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
  };
  struct {
    unsigned char :1;
    unsigned char GO:1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
  };
  struct {
    unsigned char :1;
    unsigned char NOT_DONE:1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
  };
} __ADCON0bits_t;
extern volatile __ADCON0bits_t __at(ADCON0_ADDR) ADCON0bits;

// ----- ADCON1 bits --------------------
typedef union {
  struct {
    unsigned char ADPREF0:1;
    unsigned char ADPREF1:1;
    unsigned char :1;
    unsigned char :1;
    unsigned char ADCS0:1;
    unsigned char ADCS1:1;
    unsigned char ADCS2:1;
    unsigned char ADFM:1;
  };
} __ADCON1bits_t;
extern volatile __ADCON1bits_t __at(ADCON1_ADDR) ADCON1bits;

// ----- ANSELA bits --------------------
typedef union {
  struct {
    unsigned char ANSA0:1;
    unsigned char ANSA1:1;
    unsigned char ANSA2:1;
    unsigned char ANSA3:1;
    unsigned char :1;
    unsigned char ANSA5:1;
    unsigned char :1;
    unsigned char :1;
  };
} __ANSELAbits_t;
extern volatile __ANSELAbits_t __at(ANSELA_ADDR) ANSELAbits;

// ----- ANSELB bits --------------------
typedef union {
  struct {
    unsigned char ANSB0:1;
    unsigned char ANSB1:1;
    unsigned char ANSB2:1;
    unsigned char ANSB3:1;
    unsigned char ANSB4:1;
    unsigned char ANSB5:1;
    unsigned char :1;
    unsigned char :1;
  };
} __ANSELBbits_t;
extern volatile __ANSELBbits_t __at(ANSELB_ADDR) ANSELBbits;

// ----- ANSELE bits --------------------
typedef union {
  struct {
    unsigned char ANSE0:1;
    unsigned char ANSE1:1;
    unsigned char ANSE2:1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
  };
} __ANSELEbits_t;
extern volatile __ANSELEbits_t __at(ANSELE_ADDR) ANSELEbits;

// ----- BAUD1CON bits --------------------
typedef union {
  struct {
    unsigned char ABDEN:1;
    unsigned char WUE:1;
    unsigned char :1;
    unsigned char BRG16:1;
    unsigned char SCKP:1;
    unsigned char :1;
    unsigned char RCIDL:1;
    unsigned char ABDOVF:1;
  };
} __BAUD1CONbits_t;
extern volatile __BAUD1CONbits_t __at(BAUD1CON_ADDR) BAUD1CONbits;

// ----- BAUDCON bits --------------------
typedef union {
  struct {
    unsigned char ABDEN:1;
    unsigned char WUE:1;
    unsigned char :1;
    unsigned char BRG16:1;
    unsigned char SCKP:1;
    unsigned char :1;
    unsigned char RCIDL:1;
    unsigned char ABDOVF:1;
  };
} __BAUDCONbits_t;
extern volatile __BAUDCONbits_t __at(BAUDCON_ADDR) BAUDCONbits;

// ----- BAUDCON1 bits --------------------
typedef union {
  struct {
    unsigned char ABDEN:1;
    unsigned char WUE:1;
    unsigned char :1;
    unsigned char BRG16:1;
    unsigned char SCKP:1;
    unsigned char :1;
    unsigned char RCIDL:1;
    unsigned char ABDOVF:1;
  };
} __BAUDCON1bits_t;
extern volatile __BAUDCON1bits_t __at(BAUDCON1_ADDR) BAUDCON1bits;

// ----- BORCON bits --------------------
typedef union {
  struct {
    unsigned char BORRDY:1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char BORFS:1;
    unsigned char SBOREN:1;
  };
} __BORCONbits_t;
extern volatile __BORCONbits_t __at(BORCON_ADDR) BORCONbits;

// ----- BSR bits --------------------
typedef union {
  struct {
    unsigned char BSR0:1;
    unsigned char BSR1:1;
    unsigned char BSR2:1;
    unsigned char BSR3:1;
    unsigned char BSR4:1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
  };
} __BSRbits_t;
extern volatile __BSRbits_t __at(BSR_ADDR) BSRbits;

// ----- FVRCON bits --------------------
typedef union {
  struct {
    unsigned char ADFVR0:1;
    unsigned char ADFVR1:1;
    unsigned char :1;
    unsigned char :1;
    unsigned char TSRNG:1;
    unsigned char TSEN:1;
    unsigned char FVRRDY:1;
    unsigned char FVREN:1;
  };
} __FVRCONbits_t;
extern volatile __FVRCONbits_t __at(FVRCON_ADDR) FVRCONbits;

// ----- INTCON bits --------------------
typedef union {
  struct {
    unsigned char IOCIF:1;
    unsigned char INTF:1;
    unsigned char TMR0IF:1;
    unsigned char IOCIE:1;
    unsigned char INTE:1;
    unsigned char TMR0IE:1;
    unsigned char PEIE:1;
    unsigned char GIE:1;
  };
  struct {
    unsigned char :1;
    unsigned char :1;
    unsigned char T0IF:1;
    unsigned char :1;
    unsigned char :1;
    unsigned char T0IE:1;
    unsigned char :1;
    unsigned char :1;
  };
} __INTCONbits_t;
extern volatile __INTCONbits_t __at(INTCON_ADDR) INTCONbits;

// ----- IOCBF bits --------------------
typedef union {
  struct {
    unsigned char IOCBF0:1;
    unsigned char IOCBF1:1;
    unsigned char IOCBF2:1;
    unsigned char IOCBF3:1;
    unsigned char IOCBF4:1;
    unsigned char IOCBF5:1;
    unsigned char IOCBF6:1;
    unsigned char IOCBF7:1;
  };
} __IOCBFbits_t;
extern volatile __IOCBFbits_t __at(IOCBF_ADDR) IOCBFbits;

// ----- IOCBN bits --------------------
typedef union {
  struct {
    unsigned char IOCBN0:1;
    unsigned char IOCBN1:1;
    unsigned char IOCBN2:1;
    unsigned char IOCBN3:1;
    unsigned char IOCBN4:1;
    unsigned char IOCBN5:1;
    unsigned char IOCBN6:1;
    unsigned char IOCBN7:1;
  };
} __IOCBNbits_t;
extern volatile __IOCBNbits_t __at(IOCBN_ADDR) IOCBNbits;

// ----- IOCBP bits --------------------
typedef union {
  struct {
    unsigned char IOCBP0:1;
    unsigned char IOCBP1:1;
    unsigned char IOCBP2:1;
    unsigned char IOCBP3:1;
    unsigned char IOCBP4:1;
    unsigned char IOCBP5:1;
    unsigned char IOCBP6:1;
    unsigned char IOCBP7:1;
  };
} __IOCBPbits_t;
extern volatile __IOCBPbits_t __at(IOCBP_ADDR) IOCBPbits;

// ----- LATA bits --------------------
typedef union {
  struct {
    unsigned char LATA0:1;
    unsigned char LATA1:1;
    unsigned char LATA2:1;
    unsigned char LATA3:1;
    unsigned char LATA4:1;
    unsigned char LATA5:1;
    unsigned char LATA6:1;
    unsigned char LATA7:1;
  };
} __LATAbits_t;
extern volatile __LATAbits_t __at(LATA_ADDR) LATAbits;

// ----- LATB bits --------------------
typedef union {
  struct {
    unsigned char LATB0:1;
    unsigned char LATB1:1;
    unsigned char LATB2:1;
    unsigned char LATB3:1;
    unsigned char LATB4:1;
    unsigned char LATB5:1;
    unsigned char LATB6:1;
    unsigned char LATB7:1;
  };
} __LATBbits_t;
extern volatile __LATBbits_t __at(LATB_ADDR) LATBbits;

// ----- LATC bits --------------------
typedef union {
  struct {
    unsigned char LATC0:1;
    unsigned char LATC1:1;
    unsigned char LATC2:1;
    unsigned char LATC3:1;
    unsigned char LATC4:1;
    unsigned char LATC5:1;
    unsigned char LATC6:1;
    unsigned char LATC7:1;
  };
} __LATCbits_t;
extern volatile __LATCbits_t __at(LATC_ADDR) LATCbits;

// ----- LATD bits --------------------
typedef union {
  struct {
    unsigned char LATD0:1;
    unsigned char LATD1:1;
    unsigned char LATD2:1;
    unsigned char LATD3:1;
    unsigned char LATD4:1;
    unsigned char LATD5:1;
    unsigned char LATD6:1;
    unsigned char LATD7:1;
  };
} __LATDbits_t;
extern volatile __LATDbits_t __at(LATD_ADDR) LATDbits;

// ----- LATE bits --------------------
typedef union {
  struct {
    unsigned char LATE0:1;
    unsigned char LATE1:1;
    unsigned char LATE2:1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
  };
} __LATEbits_t;
extern volatile __LATEbits_t __at(LATE_ADDR) LATEbits;

// ----- LCDCON bits --------------------
typedef union {
  struct {
    unsigned char LMUX0:1;
    unsigned char LMUX1:1;
    unsigned char CS0:1;
    unsigned char CS1:1;
    unsigned char :1;
    unsigned char WERR:1;
    unsigned char SLPEN:1;
    unsigned char LCDEN:1;
  };
} __LCDCONbits_t;
extern volatile __LCDCONbits_t __at(LCDCON_ADDR) LCDCONbits;

// ----- LCDCST bits --------------------
typedef union {
  struct {
    unsigned char LCDCST0:1;
    unsigned char LCDCST1:1;
    unsigned char LCDCST2:1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
  };
} __LCDCSTbits_t;
extern volatile __LCDCSTbits_t __at(LCDCST_ADDR) LCDCSTbits;

// ----- LCDDATA0 bits --------------------
typedef union {
  struct {
    unsigned char SEG0COM0:1;
    unsigned char SEG1COM0:1;
    unsigned char SEG2COM0:1;
    unsigned char SEG3COM0:1;
    unsigned char SEG4COM0:1;
    unsigned char SEG5COM0:1;
    unsigned char SEG6COM0:1;
    unsigned char SEG7COM0:1;
  };
} __LCDDATA0bits_t;
extern volatile __LCDDATA0bits_t __at(LCDDATA0_ADDR) LCDDATA0bits;

// ----- LCDDATA1 bits --------------------
typedef union {
  struct {
    unsigned char SEG8COM0:1;
    unsigned char SEG9COM0:1;
    unsigned char SEG10COM0:1;
    unsigned char SEG11COM0:1;
    unsigned char SEG12COM0:1;
    unsigned char SEG13COM0:1;
    unsigned char SEG14COM0:1;
    unsigned char SEG15COM0:1;
  };
} __LCDDATA1bits_t;
extern volatile __LCDDATA1bits_t __at(LCDDATA1_ADDR) LCDDATA1bits;

// ----- LCDDATA10 bits --------------------
typedef union {
  struct {
    unsigned char SEG8COM3:1;
    unsigned char SEG9COM3:1;
    unsigned char SEG10COM3:1;
    unsigned char SEG11COM3:1;
    unsigned char SEG12COM3:1;
    unsigned char SEG13COM3:1;
    unsigned char SEG14COM3:1;
    unsigned char SEG15COM3:1;
  };
} __LCDDATA10bits_t;
extern volatile __LCDDATA10bits_t __at(LCDDATA10_ADDR) LCDDATA10bits;

// ----- LCDDATA11 bits --------------------
typedef union {
  struct {
    unsigned char SEG16COM3:1;
    unsigned char SEG17COM3:1;
    unsigned char SEG18COM3:1;
    unsigned char SEG19COM3:1;
    unsigned char SEG20COM3:1;
    unsigned char SEG21COM3:1;
    unsigned char SEG22COM3:1;
    unsigned char SEG23COM3:1;
  };
} __LCDDATA11bits_t;
extern volatile __LCDDATA11bits_t __at(LCDDATA11_ADDR) LCDDATA11bits;

// ----- LCDDATA12 bits --------------------
typedef union {
  struct {
    unsigned char SEG24COM0:1;
    unsigned char SEG25COM0:1;
    unsigned char SEG26COM0:1;
    unsigned char SEG27COM0:1;
    unsigned char SEG28COM0:1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
  };
} __LCDDATA12bits_t;
extern volatile __LCDDATA12bits_t __at(LCDDATA12_ADDR) LCDDATA12bits;

// ----- LCDDATA15 bits --------------------
typedef union {
  struct {
    unsigned char SEG24COM1:1;
    unsigned char SEG25COM1:1;
    unsigned char SEG26COM1:1;
    unsigned char SEG27COM1:1;
    unsigned char SEG28COM1:1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
  };
} __LCDDATA15bits_t;
extern volatile __LCDDATA15bits_t __at(LCDDATA15_ADDR) LCDDATA15bits;

// ----- LCDDATA18 bits --------------------
typedef union {
  struct {
    unsigned char SEG24COM2:1;
    unsigned char SEG25COM2:1;
    unsigned char SEG26COM2:1;
    unsigned char SEG27COM2:1;
    unsigned char SEG28COM2:1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
  };
} __LCDDATA18bits_t;
extern volatile __LCDDATA18bits_t __at(LCDDATA18_ADDR) LCDDATA18bits;

// ----- LCDDATA2 bits --------------------
typedef union {
  struct {
    unsigned char SEG16COM0:1;
    unsigned char SEG17COM0:1;
    unsigned char SEG18COM0:1;
    unsigned char SEG19COM0:1;
    unsigned char SEG20COM0:1;
    unsigned char SEG21COM0:1;
    unsigned char SEG22COM0:1;
    unsigned char SEG23COM0:1;
  };
} __LCDDATA2bits_t;
extern volatile __LCDDATA2bits_t __at(LCDDATA2_ADDR) LCDDATA2bits;

// ----- LCDDATA21 bits --------------------
typedef union {
  struct {
    unsigned char SEG24COM3:1;
    unsigned char SEG25COM3:1;
    unsigned char SEG26COM3:1;
    unsigned char SEG27COM3:1;
    unsigned char SEG28COM3:1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
  };
} __LCDDATA21bits_t;
extern volatile __LCDDATA21bits_t __at(LCDDATA21_ADDR) LCDDATA21bits;

// ----- LCDDATA3 bits --------------------
typedef union {
  struct {
    unsigned char SEG0COM1:1;
    unsigned char SEG1COM1:1;
    unsigned char SEG2COM1:1;
    unsigned char SEG3COM1:1;
    unsigned char SEG4COM1:1;
    unsigned char SEG5COM1:1;
    unsigned char SEG6COM1:1;
    unsigned char SEG7COM1:1;
  };
} __LCDDATA3bits_t;
extern volatile __LCDDATA3bits_t __at(LCDDATA3_ADDR) LCDDATA3bits;

// ----- LCDDATA4 bits --------------------
typedef union {
  struct {
    unsigned char SEG8COM1:1;
    unsigned char SEG9COM1:1;
    unsigned char SEG10COM1:1;
    unsigned char SEG11COM1:1;
    unsigned char SEG12COM1:1;
    unsigned char SEG13COM1:1;
    unsigned char SEG14COM1:1;
    unsigned char SEG15COM1:1;
  };
} __LCDDATA4bits_t;
extern volatile __LCDDATA4bits_t __at(LCDDATA4_ADDR) LCDDATA4bits;

// ----- LCDDATA5 bits --------------------
typedef union {
  struct {
    unsigned char SEG16COM1:1;
    unsigned char SEG17COM1:1;
    unsigned char SEG18COM1:1;
    unsigned char SEG19COM1:1;
    unsigned char SEG20COM1:1;
    unsigned char SEG21COM1:1;
    unsigned char SEG22COM1:1;
    unsigned char SEG23COM1:1;
  };
} __LCDDATA5bits_t;
extern volatile __LCDDATA5bits_t __at(LCDDATA5_ADDR) LCDDATA5bits;

// ----- LCDDATA6 bits --------------------
typedef union {
  struct {
    unsigned char SEG0COM2:1;
    unsigned char SEG1COM2:1;
    unsigned char SEG2COM2:1;
    unsigned char SEG3COM2:1;
    unsigned char SEG4COM2:1;
    unsigned char SEG5COM2:1;
    unsigned char SEG6COM2:1;
    unsigned char SEG7COM2:1;
  };
} __LCDDATA6bits_t;
extern volatile __LCDDATA6bits_t __at(LCDDATA6_ADDR) LCDDATA6bits;

// ----- LCDDATA7 bits --------------------
typedef union {
  struct {
    unsigned char SEG8COM2:1;
    unsigned char SEG9COM2:1;
    unsigned char SEG10COM2:1;
    unsigned char SEG11COM2:1;
    unsigned char SEG12COM2:1;
    unsigned char SEG13COM2:1;
    unsigned char SEG14COM2:1;
    unsigned char SEG15COM2:1;
  };
} __LCDDATA7bits_t;
extern volatile __LCDDATA7bits_t __at(LCDDATA7_ADDR) LCDDATA7bits;

// ----- LCDDATA8 bits --------------------
typedef union {
  struct {
    unsigned char SEG16COM2:1;
    unsigned char SEG17COM2:1;
    unsigned char SEG18COM2:1;
    unsigned char SEG19COM2:1;
    unsigned char SEG20COM2:1;
    unsigned char SEG21COM2:1;
    unsigned char SEG22COM2:1;
    unsigned char SEG23COM2:1;
  };
} __LCDDATA8bits_t;
extern volatile __LCDDATA8bits_t __at(LCDDATA8_ADDR) LCDDATA8bits;

// ----- LCDDATA9 bits --------------------
typedef union {
  struct {
    unsigned char SEG0COM3:1;
    unsigned char SEG1COM3:1;
    unsigned char SEG2COM3:1;
    unsigned char SEG3COM3:1;
    unsigned char SEG4COM3:1;
    unsigned char SEG5COM3:1;
    unsigned char SEG6COM3:1;
    unsigned char SEG7COM3:1;
  };
} __LCDDATA9bits_t;
extern volatile __LCDDATA9bits_t __at(LCDDATA9_ADDR) LCDDATA9bits;

// ----- LCDPS bits --------------------
typedef union {
  struct {
    unsigned char LP0:1;
    unsigned char LP1:1;
    unsigned char LP2:1;
    unsigned char LP3:1;
    unsigned char WA:1;
    unsigned char LCDA:1;
    unsigned char BIASMD:1;
    unsigned char WFT:1;
  };
} __LCDPSbits_t;
extern volatile __LCDPSbits_t __at(LCDPS_ADDR) LCDPSbits;

// ----- LCDREF bits --------------------
typedef union {
  struct {
    unsigned char :1;
    unsigned char VLCD1PE:1;
    unsigned char VLCD2PE:1;
    unsigned char VLCD3PE:1;
    unsigned char :1;
    unsigned char LCDIRI:1;
    unsigned char :1;
    unsigned char LCDIRE:1;
  };
} __LCDREFbits_t;
extern volatile __LCDREFbits_t __at(LCDREF_ADDR) LCDREFbits;

// ----- LCDRL bits --------------------
typedef union {
  struct {
    unsigned char LRLAT0:1;
    unsigned char LRLAT1:1;
    unsigned char LRLAT2:1;
    unsigned char :1;
    unsigned char LRLBP0:1;
    unsigned char LRLBP1:1;
    unsigned char LRLAP0:1;
    unsigned char LRLAP1:1;
  };
} __LCDRLbits_t;
extern volatile __LCDRLbits_t __at(LCDRL_ADDR) LCDRLbits;

// ----- LCDSE0 bits --------------------
typedef union {
  struct {
    unsigned char SE0:1;
    unsigned char SE1:1;
    unsigned char SE2:1;
    unsigned char SE3:1;
    unsigned char SE4:1;
    unsigned char SE5:1;
    unsigned char SE6:1;
    unsigned char SE7:1;
  };
} __LCDSE0bits_t;
extern volatile __LCDSE0bits_t __at(LCDSE0_ADDR) LCDSE0bits;

// ----- LCDSE1 bits --------------------
typedef union {
  struct {
    unsigned char SE8:1;
    unsigned char SE9:1;
    unsigned char SE10:1;
    unsigned char SE11:1;
    unsigned char SE12:1;
    unsigned char SE13:1;
    unsigned char SE14:1;
    unsigned char SE15:1;
  };
} __LCDSE1bits_t;
extern volatile __LCDSE1bits_t __at(LCDSE1_ADDR) LCDSE1bits;

// ----- LCDSE2 bits --------------------
typedef union {
  struct {
    unsigned char SE16:1;
    unsigned char SE17:1;
    unsigned char SE18:1;
    unsigned char SE19:1;
    unsigned char SE20:1;
    unsigned char SE21:1;
    unsigned char SE22:1;
    unsigned char SE23:1;
  };
  struct {
    unsigned char SE24:1;
    unsigned char SE25:1;
    unsigned char SE26:1;
    unsigned char SE27:1;
    unsigned char SE28:1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
  };
} __LCDSE2bits_t;
extern volatile __LCDSE2bits_t __at(LCDSE2_ADDR) LCDSE2bits;

// ----- OPTION_REG bits --------------------
typedef union {
  struct {
    unsigned char PS0:1;
    unsigned char PS1:1;
    unsigned char PS2:1;
    unsigned char PSA:1;
    unsigned char TMR0SE:1;
    unsigned char TMR0CS:1;
    unsigned char INTEDG:1;
    unsigned char NOT_WPUEN:1;
  };
  struct {
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char T0SE:1;
    unsigned char T0CS:1;
    unsigned char :1;
    unsigned char :1;
  };
} __OPTION_REGbits_t;
extern volatile __OPTION_REGbits_t __at(OPTION_REG_ADDR) OPTION_REGbits;

// ----- OSCCON bits --------------------
typedef union {
  struct {
    unsigned char SCS0:1;
    unsigned char SCS1:1;
    unsigned char :1;
    unsigned char IRCF0:1;
    unsigned char IRCF1:1;
    unsigned char IRCF2:1;
    unsigned char IRCF3:1;
    unsigned char :1;
  };
} __OSCCONbits_t;
extern volatile __OSCCONbits_t __at(OSCCON_ADDR) OSCCONbits;

// ----- OSCSTAT bits --------------------
typedef union {
  struct {
    unsigned char HFIOFS:1;
    unsigned char LFIOFR:1;
    unsigned char :1;
    unsigned char :1;
    unsigned char HFIOFR:1;
    unsigned char OSTS:1;
    unsigned char :1;
    unsigned char T1OSCR:1;
  };
} __OSCSTATbits_t;
extern volatile __OSCSTATbits_t __at(OSCSTAT_ADDR) OSCSTATbits;

// ----- PCON bits --------------------
typedef union {
  struct {
    unsigned char NOT_BOR:1;
    unsigned char NOT_POR:1;
    unsigned char NOT_RI:1;
    unsigned char NOT_RMCLR:1;
    unsigned char NOT_RWDT:1;
    unsigned char :1;
    unsigned char STKUNF:1;
    unsigned char STKOVF:1;
  };
} __PCONbits_t;
extern volatile __PCONbits_t __at(PCON_ADDR) PCONbits;

// ----- PIE1 bits --------------------
typedef union {
  struct {
    unsigned char TMR1IE:1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char TXIE:1;
    unsigned char RCIE:1;
    unsigned char ADIE:1;
    unsigned char TMR1GIE:1;
  };
} __PIE1bits_t;
extern volatile __PIE1bits_t __at(PIE1_ADDR) PIE1bits;

// ----- PIE2 bits --------------------
typedef union {
  struct {
    unsigned char :1;
    unsigned char :1;
    unsigned char LCDIE:1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
  };
} __PIE2bits_t;
extern volatile __PIE2bits_t __at(PIE2_ADDR) PIE2bits;

// ----- PIR1 bits --------------------
typedef union {
  struct {
    unsigned char TMR1IF:1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char TXIF:1;
    unsigned char RCIF:1;
    unsigned char ADIF:1;
    unsigned char TMR1GIF:1;
  };
} __PIR1bits_t;
extern volatile __PIR1bits_t __at(PIR1_ADDR) PIR1bits;

// ----- PIR2 bits --------------------
typedef union {
  struct {
    unsigned char :1;
    unsigned char :1;
    unsigned char LCDIF:1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
  };
} __PIR2bits_t;
extern volatile __PIR2bits_t __at(PIR2_ADDR) PIR2bits;

// ----- PMCON1 bits --------------------
typedef union {
  struct {
    unsigned char RD:1;
    unsigned char WR:1;
    unsigned char WREN:1;
    unsigned char WRERR:1;
    unsigned char FREE:1;
    unsigned char LWLO:1;
    unsigned char CFGS:1;
    unsigned char :1;
  };
} __PMCON1bits_t;
extern volatile __PMCON1bits_t __at(PMCON1_ADDR) PMCON1bits;

// ----- PORTA bits --------------------
typedef union {
  struct {
    unsigned char RA0:1;
    unsigned char RA1:1;
    unsigned char RA2:1;
    unsigned char RA3:1;
    unsigned char RA4:1;
    unsigned char RA5:1;
    unsigned char RA6:1;
    unsigned char RA7:1;
  };
} __PORTAbits_t;
extern volatile __PORTAbits_t __at(PORTA_ADDR) PORTAbits;

// ----- PORTB bits --------------------
typedef union {
  struct {
    unsigned char RB0:1;
    unsigned char RB1:1;
    unsigned char RB2:1;
    unsigned char RB3:1;
    unsigned char RB4:1;
    unsigned char RB5:1;
    unsigned char RB6:1;
    unsigned char RB7:1;
  };
} __PORTBbits_t;
extern volatile __PORTBbits_t __at(PORTB_ADDR) PORTBbits;

// ----- PORTC bits --------------------
typedef union {
  struct {
    unsigned char RC0:1;
    unsigned char RC1:1;
    unsigned char RC2:1;
    unsigned char RC3:1;
    unsigned char RC4:1;
    unsigned char RC5:1;
    unsigned char RC6:1;
    unsigned char RC7:1;
  };
} __PORTCbits_t;
extern volatile __PORTCbits_t __at(PORTC_ADDR) PORTCbits;

// ----- PORTD bits --------------------
typedef union {
  struct {
    unsigned char RD0:1;
    unsigned char RD1:1;
    unsigned char RD2:1;
    unsigned char RD3:1;
    unsigned char RD4:1;
    unsigned char RD5:1;
    unsigned char RD6:1;
    unsigned char RD7:1;
  };
} __PORTDbits_t;
extern volatile __PORTDbits_t __at(PORTD_ADDR) PORTDbits;

// ----- PORTE bits --------------------
typedef union {
  struct {
    unsigned char RE0:1;
    unsigned char RE1:1;
    unsigned char RE2:1;
    unsigned char RE3:1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
  };
} __PORTEbits_t;
extern volatile __PORTEbits_t __at(PORTE_ADDR) PORTEbits;

// ----- RC1STA bits --------------------
typedef union {
  struct {
    unsigned char RX9D:1;
    unsigned char OERR:1;
    unsigned char FERR:1;
    unsigned char ADDEN:1;
    unsigned char CREN:1;
    unsigned char SREN:1;
    unsigned char RX9:1;
    unsigned char SPEN:1;
  };
} __RC1STAbits_t;
extern volatile __RC1STAbits_t __at(RC1STA_ADDR) RC1STAbits;

// ----- RCSTA bits --------------------
typedef union {
  struct {
    unsigned char RX9D:1;
    unsigned char OERR:1;
    unsigned char FERR:1;
    unsigned char ADDEN:1;
    unsigned char CREN:1;
    unsigned char SREN:1;
    unsigned char RX9:1;
    unsigned char SPEN:1;
  };
} __RCSTAbits_t;
extern volatile __RCSTAbits_t __at(RCSTA_ADDR) RCSTAbits;

// ----- RCSTA1 bits --------------------
typedef union {
  struct {
    unsigned char RX9D:1;
    unsigned char OERR:1;
    unsigned char FERR:1;
    unsigned char ADDEN:1;
    unsigned char CREN:1;
    unsigned char SREN:1;
    unsigned char RX9:1;
    unsigned char SPEN:1;
  };
} __RCSTA1bits_t;
extern volatile __RCSTA1bits_t __at(RCSTA1_ADDR) RCSTA1bits;

// ----- SP1BRGH bits --------------------
typedef union {
  struct {
    unsigned char BRG8:1;
    unsigned char BRG9:1;
    unsigned char BRG10:1;
    unsigned char BRG11:1;
    unsigned char BRG12:1;
    unsigned char BRG13:1;
    unsigned char BRG14:1;
    unsigned char BRG15:1;
  };
} __SP1BRGHbits_t;
extern volatile __SP1BRGHbits_t __at(SP1BRGH_ADDR) SP1BRGHbits;

// ----- SP1BRGL bits --------------------
typedef union {
  struct {
    unsigned char BRG0:1;
    unsigned char BRG1:1;
    unsigned char BRG2:1;
    unsigned char BRG3:1;
    unsigned char BRG4:1;
    unsigned char BRG5:1;
    unsigned char BRG6:1;
    unsigned char BRG7:1;
  };
} __SP1BRGLbits_t;
extern volatile __SP1BRGLbits_t __at(SP1BRGL_ADDR) SP1BRGLbits;

// ----- SPBRG bits --------------------
typedef union {
  struct {
    unsigned char BRG0:1;
    unsigned char BRG1:1;
    unsigned char BRG2:1;
    unsigned char BRG3:1;
    unsigned char BRG4:1;
    unsigned char BRG5:1;
    unsigned char BRG6:1;
    unsigned char BRG7:1;
  };
} __SPBRGbits_t;
extern volatile __SPBRGbits_t __at(SPBRG_ADDR) SPBRGbits;

// ----- SPBRGH bits --------------------
typedef union {
  struct {
    unsigned char BRG8:1;
    unsigned char BRG9:1;
    unsigned char BRG10:1;
    unsigned char BRG11:1;
    unsigned char BRG12:1;
    unsigned char BRG13:1;
    unsigned char BRG14:1;
    unsigned char BRG15:1;
  };
} __SPBRGHbits_t;
extern volatile __SPBRGHbits_t __at(SPBRGH_ADDR) SPBRGHbits;

// ----- SPBRGH1 bits --------------------
typedef union {
  struct {
    unsigned char BRG8:1;
    unsigned char BRG9:1;
    unsigned char BRG10:1;
    unsigned char BRG11:1;
    unsigned char BRG12:1;
    unsigned char BRG13:1;
    unsigned char BRG14:1;
    unsigned char BRG15:1;
  };
} __SPBRGH1bits_t;
extern volatile __SPBRGH1bits_t __at(SPBRGH1_ADDR) SPBRGH1bits;

// ----- SPBRGL bits --------------------
typedef union {
  struct {
    unsigned char BRG0:1;
    unsigned char BRG1:1;
    unsigned char BRG2:1;
    unsigned char BRG3:1;
    unsigned char BRG4:1;
    unsigned char BRG5:1;
    unsigned char BRG6:1;
    unsigned char BRG7:1;
  };
} __SPBRGLbits_t;
extern volatile __SPBRGLbits_t __at(SPBRGL_ADDR) SPBRGLbits;

// ----- SPBRGL1 bits --------------------
typedef union {
  struct {
    unsigned char BRG0:1;
    unsigned char BRG1:1;
    unsigned char BRG2:1;
    unsigned char BRG3:1;
    unsigned char BRG4:1;
    unsigned char BRG5:1;
    unsigned char BRG6:1;
    unsigned char BRG7:1;
  };
} __SPBRGL1bits_t;
extern volatile __SPBRGL1bits_t __at(SPBRGL1_ADDR) SPBRGL1bits;

// ----- STATUS bits --------------------
typedef union {
  struct {
    unsigned char C:1;
    unsigned char DC:1;
    unsigned char Z:1;
    unsigned char NOT_PD:1;
    unsigned char NOT_TO:1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
  };
} __STATUSbits_t;
extern volatile __STATUSbits_t __at(STATUS_ADDR) STATUSbits;

// ----- STATUS_SHAD bits --------------------
typedef union {
  struct {
    unsigned char C_SHAD:1;
    unsigned char DC_SHAD:1;
    unsigned char Z_SHAD:1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
  };
} __STATUS_SHADbits_t;
extern volatile __STATUS_SHADbits_t __at(STATUS_SHAD_ADDR) STATUS_SHADbits;

// ----- T1CON bits --------------------
typedef union {
  struct {
    unsigned char TMR1ON:1;
    unsigned char :1;
    unsigned char NOT_T1SYNC:1;
    unsigned char T1OSCEN:1;
    unsigned char T1CKPS0:1;
    unsigned char T1CKPS1:1;
    unsigned char TMR1CS0:1;
    unsigned char TMR1CS1:1;
  };
} __T1CONbits_t;
extern volatile __T1CONbits_t __at(T1CON_ADDR) T1CONbits;

// ----- T1GCON bits --------------------
typedef union {
  struct {
    unsigned char T1GSS0:1;
    unsigned char T1GSS1:1;
    unsigned char T1GVAL:1;
    unsigned char T1GGO_NOT_DONE:1;
    unsigned char T1GSPM:1;
    unsigned char T1GTM:1;
    unsigned char T1GPOL:1;
    unsigned char TMR1GE:1;
  };
  struct {
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char T1GGO:1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
  };
} __T1GCONbits_t;
extern volatile __T1GCONbits_t __at(T1GCON_ADDR) T1GCONbits;

// ----- TRISA bits --------------------
typedef union {
  struct {
    unsigned char TRISA0:1;
    unsigned char TRISA1:1;
    unsigned char TRISA2:1;
    unsigned char TRISA3:1;
    unsigned char TRISA4:1;
    unsigned char TRISA5:1;
    unsigned char TRISA6:1;
    unsigned char TRISA7:1;
  };
} __TRISAbits_t;
extern volatile __TRISAbits_t __at(TRISA_ADDR) TRISAbits;

// ----- TRISB bits --------------------
typedef union {
  struct {
    unsigned char TRISB0:1;
    unsigned char TRISB1:1;
    unsigned char TRISB2:1;
    unsigned char TRISB3:1;
    unsigned char TRISB4:1;
    unsigned char TRISB5:1;
    unsigned char TRISB6:1;
    unsigned char TRISB7:1;
  };
} __TRISBbits_t;
extern volatile __TRISBbits_t __at(TRISB_ADDR) TRISBbits;

// ----- TRISC bits --------------------
typedef union {
  struct {
    unsigned char TRISC0:1;
    unsigned char TRISC1:1;
    unsigned char TRISC2:1;
    unsigned char TRISC3:1;
    unsigned char TRISC4:1;
    unsigned char TRISC5:1;
    unsigned char TRISC6:1;
    unsigned char TRISC7:1;
  };
} __TRISCbits_t;
extern volatile __TRISCbits_t __at(TRISC_ADDR) TRISCbits;

// ----- TRISD bits --------------------
typedef union {
  struct {
    unsigned char TRISD0:1;
    unsigned char TRISD1:1;
    unsigned char TRISD2:1;
    unsigned char TRISD3:1;
    unsigned char TRISD4:1;
    unsigned char TRISD5:1;
    unsigned char TRISD6:1;
    unsigned char TRISD7:1;
  };
} __TRISDbits_t;
extern volatile __TRISDbits_t __at(TRISD_ADDR) TRISDbits;

// ----- TRISE bits --------------------
typedef union {
  struct {
    unsigned char TRISE0:1;
    unsigned char TRISE1:1;
    unsigned char TRISE2:1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
  };
} __TRISEbits_t;
extern volatile __TRISEbits_t __at(TRISE_ADDR) TRISEbits;

// ----- TX1STA bits --------------------
typedef union {
  struct {
    unsigned char TX9D:1;
    unsigned char TRMT:1;
    unsigned char BRGH:1;
    unsigned char SENDB:1;
    unsigned char SYNC:1;
    unsigned char TXEN:1;
    unsigned char TX9:1;
    unsigned char CSRC:1;
  };
} __TX1STAbits_t;
extern volatile __TX1STAbits_t __at(TX1STA_ADDR) TX1STAbits;

// ----- TXSTA bits --------------------
typedef union {
  struct {
    unsigned char TX9D:1;
    unsigned char TRMT:1;
    unsigned char BRGH:1;
    unsigned char SENDB:1;
    unsigned char SYNC:1;
    unsigned char TXEN:1;
    unsigned char TX9:1;
    unsigned char CSRC:1;
  };
} __TXSTAbits_t;
extern volatile __TXSTAbits_t __at(TXSTA_ADDR) TXSTAbits;

// ----- TXSTA1 bits --------------------
typedef union {
  struct {
    unsigned char TX9D:1;
    unsigned char TRMT:1;
    unsigned char BRGH:1;
    unsigned char SENDB:1;
    unsigned char SYNC:1;
    unsigned char TXEN:1;
    unsigned char TX9:1;
    unsigned char CSRC:1;
  };
} __TXSTA1bits_t;
extern volatile __TXSTA1bits_t __at(TXSTA1_ADDR) TXSTA1bits;

// ----- WDTCON bits --------------------
typedef union {
  struct {
    unsigned char SWDTEN:1;
    unsigned char WDTPS0:1;
    unsigned char WDTPS1:1;
    unsigned char WDTPS2:1;
    unsigned char WDTPS3:1;
    unsigned char WDTPS4:1;
    unsigned char :1;
    unsigned char :1;
  };
} __WDTCONbits_t;
extern volatile __WDTCONbits_t __at(WDTCON_ADDR) WDTCONbits;

// ----- WPUB bits --------------------
typedef union {
  struct {
    unsigned char WPUB0:1;
    unsigned char WPUB1:1;
    unsigned char WPUB2:1;
    unsigned char WPUB3:1;
    unsigned char WPUB4:1;
    unsigned char WPUB5:1;
    unsigned char WPUB6:1;
    unsigned char WPUB7:1;
  };
} __WPUBbits_t;
extern volatile __WPUBbits_t __at(WPUB_ADDR) WPUBbits;

// ----- WPUE bits --------------------
typedef union {
  struct {
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char WPUE3:1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
    unsigned char :1;
  };
} __WPUEbits_t;
extern volatile __WPUEbits_t __at(WPUE_ADDR) WPUEbits;


#ifndef NO_BIT_DEFINES

#define ADON                 ADCON0bits.ADON                /* bit 0 */
#define ADGO                 ADCON0bits.ADGO                /* bit 1 */
#define GO                   ADCON0bits.GO                  /* bit 1 */
#define GO_NOT_DONE          ADCON0bits.GO_NOT_DONE         /* bit 1 */
#define NOT_DONE             ADCON0bits.NOT_DONE            /* bit 1 */
#define CHS0                 ADCON0bits.CHS0                /* bit 2 */
#define CHS1                 ADCON0bits.CHS1                /* bit 3 */
#define CHS2                 ADCON0bits.CHS2                /* bit 4 */
#define CHS3                 ADCON0bits.CHS3                /* bit 5 */
#define CHS4                 ADCON0bits.CHS4                /* bit 6 */

#define ADPREF0              ADCON1bits.ADPREF0             /* bit 0 */
#define ADPREF1              ADCON1bits.ADPREF1             /* bit 1 */
#define ADCS0                ADCON1bits.ADCS0               /* bit 4 */
#define ADCS1                ADCON1bits.ADCS1               /* bit 5 */
#define ADCS2                ADCON1bits.ADCS2               /* bit 6 */
#define ADFM                 ADCON1bits.ADFM                /* bit 7 */

#define ANSA0                ANSELAbits.ANSA0               /* bit 0 */
#define ANSA1                ANSELAbits.ANSA1               /* bit 1 */
#define ANSA2                ANSELAbits.ANSA2               /* bit 2 */
#define ANSA3                ANSELAbits.ANSA3               /* bit 3 */
#define ANSA5                ANSELAbits.ANSA5               /* bit 5 */

#define ANSB0                ANSELBbits.ANSB0               /* bit 0 */
#define ANSB1                ANSELBbits.ANSB1               /* bit 1 */
#define ANSB2                ANSELBbits.ANSB2               /* bit 2 */
#define ANSB3                ANSELBbits.ANSB3               /* bit 3 */
#define ANSB4                ANSELBbits.ANSB4               /* bit 4 */
#define ANSB5                ANSELBbits.ANSB5               /* bit 5 */

#define ANSE0                ANSELEbits.ANSE0               /* bit 0 */
#define ANSE1                ANSELEbits.ANSE1               /* bit 1 */
#define ANSE2                ANSELEbits.ANSE2               /* bit 2 */

#define ABDEN                BAUD1CONbits.ABDEN             /* bit 0, shadows bit in BAUDCONbits, BAUDCON1bits */
#define WUE                  BAUD1CONbits.WUE               /* bit 1, shadows bit in BAUDCONbits, BAUDCON1bits */
#define BRG16                BAUD1CONbits.BRG16             /* bit 3, shadows bit in BAUDCONbits, BAUDCON1bits */
#define SCKP                 BAUD1CONbits.SCKP              /* bit 4, shadows bit in BAUDCONbits, BAUDCON1bits */
#define RCIDL                BAUD1CONbits.RCIDL             /* bit 6, shadows bit in BAUDCONbits, BAUDCON1bits */
#define ABDOVF               BAUD1CONbits.ABDOVF            /* bit 7, shadows bit in BAUDCONbits, BAUDCON1bits */

#define BORRDY               BORCONbits.BORRDY              /* bit 0 */
#define BORFS                BORCONbits.BORFS               /* bit 6 */
#define SBOREN               BORCONbits.SBOREN              /* bit 7 */

#define BSR0                 BSRbits.BSR0                   /* bit 0 */
#define BSR1                 BSRbits.BSR1                   /* bit 1 */
#define BSR2                 BSRbits.BSR2                   /* bit 2 */
#define BSR3                 BSRbits.BSR3                   /* bit 3 */
#define BSR4                 BSRbits.BSR4                   /* bit 4 */

#define ADFVR0               FVRCONbits.ADFVR0              /* bit 0 */
#define ADFVR1               FVRCONbits.ADFVR1              /* bit 1 */
#define TSRNG                FVRCONbits.TSRNG               /* bit 4 */
#define TSEN                 FVRCONbits.TSEN                /* bit 5 */
#define FVRRDY               FVRCONbits.FVRRDY              /* bit 6 */
#define FVREN                FVRCONbits.FVREN               /* bit 7 */

#define IOCIF                INTCONbits.IOCIF               /* bit 0 */
#define INTF                 INTCONbits.INTF                /* bit 1 */
#define T0IF                 INTCONbits.T0IF                /* bit 2 */
#define TMR0IF               INTCONbits.TMR0IF              /* bit 2 */
#define IOCIE                INTCONbits.IOCIE               /* bit 3 */
#define INTE                 INTCONbits.INTE                /* bit 4 */
#define T0IE                 INTCONbits.T0IE                /* bit 5 */
#define TMR0IE               INTCONbits.TMR0IE              /* bit 5 */
#define PEIE                 INTCONbits.PEIE                /* bit 6 */
#define GIE                  INTCONbits.GIE                 /* bit 7 */

#define IOCBF0               IOCBFbits.IOCBF0               /* bit 0 */
#define IOCBF1               IOCBFbits.IOCBF1               /* bit 1 */
#define IOCBF2               IOCBFbits.IOCBF2               /* bit 2 */
#define IOCBF3               IOCBFbits.IOCBF3               /* bit 3 */
#define IOCBF4               IOCBFbits.IOCBF4               /* bit 4 */
#define IOCBF5               IOCBFbits.IOCBF5               /* bit 5 */
#define IOCBF6               IOCBFbits.IOCBF6               /* bit 6 */
#define IOCBF7               IOCBFbits.IOCBF7               /* bit 7 */

#define IOCBN0               IOCBNbits.IOCBN0               /* bit 0 */
#define IOCBN1               IOCBNbits.IOCBN1               /* bit 1 */
#define IOCBN2               IOCBNbits.IOCBN2               /* bit 2 */
#define IOCBN3               IOCBNbits.IOCBN3               /* bit 3 */
#define IOCBN4               IOCBNbits.IOCBN4               /* bit 4 */
#define IOCBN5               IOCBNbits.IOCBN5               /* bit 5 */
#define IOCBN6               IOCBNbits.IOCBN6               /* bit 6 */
#define IOCBN7               IOCBNbits.IOCBN7               /* bit 7 */

#define IOCBP0               IOCBPbits.IOCBP0               /* bit 0 */
#define IOCBP1               IOCBPbits.IOCBP1               /* bit 1 */
#define IOCBP2               IOCBPbits.IOCBP2               /* bit 2 */
#define IOCBP3               IOCBPbits.IOCBP3               /* bit 3 */
#define IOCBP4               IOCBPbits.IOCBP4               /* bit 4 */
#define IOCBP5               IOCBPbits.IOCBP5               /* bit 5 */
#define IOCBP6               IOCBPbits.IOCBP6               /* bit 6 */
#define IOCBP7               IOCBPbits.IOCBP7               /* bit 7 */

#define LATA0                LATAbits.LATA0                 /* bit 0 */
#define LATA1                LATAbits.LATA1                 /* bit 1 */
#define LATA2                LATAbits.LATA2                 /* bit 2 */
#define LATA3                LATAbits.LATA3                 /* bit 3 */
#define LATA4                LATAbits.LATA4                 /* bit 4 */
#define LATA5                LATAbits.LATA5                 /* bit 5 */
#define LATA6                LATAbits.LATA6                 /* bit 6 */
#define LATA7                LATAbits.LATA7                 /* bit 7 */

#define LATB0                LATBbits.LATB0                 /* bit 0 */
#define LATB1                LATBbits.LATB1                 /* bit 1 */
#define LATB2                LATBbits.LATB2                 /* bit 2 */
#define LATB3                LATBbits.LATB3                 /* bit 3 */
#define LATB4                LATBbits.LATB4                 /* bit 4 */
#define LATB5                LATBbits.LATB5                 /* bit 5 */
#define LATB6                LATBbits.LATB6                 /* bit 6 */
#define LATB7                LATBbits.LATB7                 /* bit 7 */

#define LATC0                LATCbits.LATC0                 /* bit 0 */
#define LATC1                LATCbits.LATC1                 /* bit 1 */
#define LATC2                LATCbits.LATC2                 /* bit 2 */
#define LATC3                LATCbits.LATC3                 /* bit 3 */
#define LATC4                LATCbits.LATC4                 /* bit 4 */
#define LATC5                LATCbits.LATC5                 /* bit 5 */
#define LATC6                LATCbits.LATC6                 /* bit 6 */
#define LATC7                LATCbits.LATC7                 /* bit 7 */

#define LATD0                LATDbits.LATD0                 /* bit 0 */
#define LATD1                LATDbits.LATD1                 /* bit 1 */
#define LATD2                LATDbits.LATD2                 /* bit 2 */
#define LATD3                LATDbits.LATD3                 /* bit 3 */
#define LATD4                LATDbits.LATD4                 /* bit 4 */
#define LATD5                LATDbits.LATD5                 /* bit 5 */
#define LATD6                LATDbits.LATD6                 /* bit 6 */
#define LATD7                LATDbits.LATD7                 /* bit 7 */

#define LATE0                LATEbits.LATE0                 /* bit 0 */
#define LATE1                LATEbits.LATE1                 /* bit 1 */
#define LATE2                LATEbits.LATE2                 /* bit 2 */

#define LMUX0                LCDCONbits.LMUX0               /* bit 0 */
#define LMUX1                LCDCONbits.LMUX1               /* bit 1 */
#define CS0                  LCDCONbits.CS0                 /* bit 2 */
#define CS1                  LCDCONbits.CS1                 /* bit 3 */
#define WERR                 LCDCONbits.WERR                /* bit 5 */
#define SLPEN                LCDCONbits.SLPEN               /* bit 6 */
#define LCDEN                LCDCONbits.LCDEN               /* bit 7 */

#define LCDCST0              LCDCSTbits.LCDCST0             /* bit 0 */
#define LCDCST1              LCDCSTbits.LCDCST1             /* bit 1 */
#define LCDCST2              LCDCSTbits.LCDCST2             /* bit 2 */

#define SEG0COM0             LCDDATA0bits.SEG0COM0          /* bit 0 */
#define SEG1COM0             LCDDATA0bits.SEG1COM0          /* bit 1 */
#define SEG2COM0             LCDDATA0bits.SEG2COM0          /* bit 2 */
#define SEG3COM0             LCDDATA0bits.SEG3COM0          /* bit 3 */
#define SEG4COM0             LCDDATA0bits.SEG4COM0          /* bit 4 */
#define SEG5COM0             LCDDATA0bits.SEG5COM0          /* bit 5 */
#define SEG6COM0             LCDDATA0bits.SEG6COM0          /* bit 6 */
#define SEG7COM0             LCDDATA0bits.SEG7COM0          /* bit 7 */

#define SEG8COM3             LCDDATA10bits.SEG8COM3         /* bit 0 */
#define SEG9COM3             LCDDATA10bits.SEG9COM3         /* bit 1 */
#define SEG10COM3            LCDDATA10bits.SEG10COM3        /* bit 2 */
#define SEG11COM3            LCDDATA10bits.SEG11COM3        /* bit 3 */
#define SEG12COM3            LCDDATA10bits.SEG12COM3        /* bit 4 */
#define SEG13COM3            LCDDATA10bits.SEG13COM3        /* bit 5 */
#define SEG14COM3            LCDDATA10bits.SEG14COM3        /* bit 6 */
#define SEG15COM3            LCDDATA10bits.SEG15COM3        /* bit 7 */

#define SEG16COM3            LCDDATA11bits.SEG16COM3        /* bit 0 */
#define SEG17COM3            LCDDATA11bits.SEG17COM3        /* bit 1 */
#define SEG18COM3            LCDDATA11bits.SEG18COM3        /* bit 2 */
#define SEG19COM3            LCDDATA11bits.SEG19COM3        /* bit 3 */
#define SEG20COM3            LCDDATA11bits.SEG20COM3        /* bit 4 */
#define SEG21COM3            LCDDATA11bits.SEG21COM3        /* bit 5 */
#define SEG22COM3            LCDDATA11bits.SEG22COM3        /* bit 6 */
#define SEG23COM3            LCDDATA11bits.SEG23COM3        /* bit 7 */

#define SEG24COM0            LCDDATA12bits.SEG24COM0        /* bit 0 */
#define SEG25COM0            LCDDATA12bits.SEG25COM0        /* bit 1 */
#define SEG26COM0            LCDDATA12bits.SEG26COM0        /* bit 2 */
#define SEG27COM0            LCDDATA12bits.SEG27COM0        /* bit 3 */
#define SEG28COM0            LCDDATA12bits.SEG28COM0        /* bit 4 */

#define SEG24COM1            LCDDATA15bits.SEG24COM1        /* bit 0 */
#define SEG25COM1            LCDDATA15bits.SEG25COM1        /* bit 1 */
#define SEG26COM1            LCDDATA15bits.SEG26COM1        /* bit 2 */
#define SEG27COM1            LCDDATA15bits.SEG27COM1        /* bit 3 */
#define SEG28COM1            LCDDATA15bits.SEG28COM1        /* bit 4 */

#define SEG24COM2            LCDDATA18bits.SEG24COM2        /* bit 0 */
#define SEG25COM2            LCDDATA18bits.SEG25COM2        /* bit 1 */
#define SEG26COM2            LCDDATA18bits.SEG26COM2        /* bit 2 */
#define SEG27COM2            LCDDATA18bits.SEG27COM2        /* bit 3 */
#define SEG28COM2            LCDDATA18bits.SEG28COM2        /* bit 4 */

#define SEG8COM0             LCDDATA1bits.SEG8COM0          /* bit 0 */
#define SEG9COM0             LCDDATA1bits.SEG9COM0          /* bit 1 */
#define SEG10COM0            LCDDATA1bits.SEG10COM0         /* bit 2 */
#define SEG11COM0            LCDDATA1bits.SEG11COM0         /* bit 3 */
#define SEG12COM0            LCDDATA1bits.SEG12COM0         /* bit 4 */
#define SEG13COM0            LCDDATA1bits.SEG13COM0         /* bit 5 */
#define SEG14COM0            LCDDATA1bits.SEG14COM0         /* bit 6 */
#define SEG15COM0            LCDDATA1bits.SEG15COM0         /* bit 7 */

#define SEG24COM3            LCDDATA21bits.SEG24COM3        /* bit 0 */
#define SEG25COM3            LCDDATA21bits.SEG25COM3        /* bit 1 */
#define SEG26COM3            LCDDATA21bits.SEG26COM3        /* bit 2 */
#define SEG27COM3            LCDDATA21bits.SEG27COM3        /* bit 3 */
#define SEG28COM3            LCDDATA21bits.SEG28COM3        /* bit 4 */

#define SEG16COM0            LCDDATA2bits.SEG16COM0         /* bit 0 */
#define SEG17COM0            LCDDATA2bits.SEG17COM0         /* bit 1 */
#define SEG18COM0            LCDDATA2bits.SEG18COM0         /* bit 2 */
#define SEG19COM0            LCDDATA2bits.SEG19COM0         /* bit 3 */
#define SEG20COM0            LCDDATA2bits.SEG20COM0         /* bit 4 */
#define SEG21COM0            LCDDATA2bits.SEG21COM0         /* bit 5 */
#define SEG22COM0            LCDDATA2bits.SEG22COM0         /* bit 6 */
#define SEG23COM0            LCDDATA2bits.SEG23COM0         /* bit 7 */

#define SEG0COM1             LCDDATA3bits.SEG0COM1          /* bit 0 */
#define SEG1COM1             LCDDATA3bits.SEG1COM1          /* bit 1 */
#define SEG2COM1             LCDDATA3bits.SEG2COM1          /* bit 2 */
#define SEG3COM1             LCDDATA3bits.SEG3COM1          /* bit 3 */
#define SEG4COM1             LCDDATA3bits.SEG4COM1          /* bit 4 */
#define SEG5COM1             LCDDATA3bits.SEG5COM1          /* bit 5 */
#define SEG6COM1             LCDDATA3bits.SEG6COM1          /* bit 6 */
#define SEG7COM1             LCDDATA3bits.SEG7COM1          /* bit 7 */

#define SEG8COM1             LCDDATA4bits.SEG8COM1          /* bit 0 */
#define SEG9COM1             LCDDATA4bits.SEG9COM1          /* bit 1 */
#define SEG10COM1            LCDDATA4bits.SEG10COM1         /* bit 2 */
#define SEG11COM1            LCDDATA4bits.SEG11COM1         /* bit 3 */
#define SEG12COM1            LCDDATA4bits.SEG12COM1         /* bit 4 */
#define SEG13COM1            LCDDATA4bits.SEG13COM1         /* bit 5 */
#define SEG14COM1            LCDDATA4bits.SEG14COM1         /* bit 6 */
#define SEG15COM1            LCDDATA4bits.SEG15COM1         /* bit 7 */

#define SEG16COM1            LCDDATA5bits.SEG16COM1         /* bit 0 */
#define SEG17COM1            LCDDATA5bits.SEG17COM1         /* bit 1 */
#define SEG18COM1            LCDDATA5bits.SEG18COM1         /* bit 2 */
#define SEG19COM1            LCDDATA5bits.SEG19COM1         /* bit 3 */
#define SEG20COM1            LCDDATA5bits.SEG20COM1         /* bit 4 */
#define SEG21COM1            LCDDATA5bits.SEG21COM1         /* bit 5 */
#define SEG22COM1            LCDDATA5bits.SEG22COM1         /* bit 6 */
#define SEG23COM1            LCDDATA5bits.SEG23COM1         /* bit 7 */

#define SEG0COM2             LCDDATA6bits.SEG0COM2          /* bit 0 */
#define SEG1COM2             LCDDATA6bits.SEG1COM2          /* bit 1 */
#define SEG2COM2             LCDDATA6bits.SEG2COM2          /* bit 2 */
#define SEG3COM2             LCDDATA6bits.SEG3COM2          /* bit 3 */
#define SEG4COM2             LCDDATA6bits.SEG4COM2          /* bit 4 */
#define SEG5COM2             LCDDATA6bits.SEG5COM2          /* bit 5 */
#define SEG6COM2             LCDDATA6bits.SEG6COM2          /* bit 6 */
#define SEG7COM2             LCDDATA6bits.SEG7COM2          /* bit 7 */

#define SEG8COM2             LCDDATA7bits.SEG8COM2          /* bit 0 */
#define SEG9COM2             LCDDATA7bits.SEG9COM2          /* bit 1 */
#define SEG10COM2            LCDDATA7bits.SEG10COM2         /* bit 2 */
#define SEG11COM2            LCDDATA7bits.SEG11COM2         /* bit 3 */
#define SEG12COM2            LCDDATA7bits.SEG12COM2         /* bit 4 */
#define SEG13COM2            LCDDATA7bits.SEG13COM2         /* bit 5 */
#define SEG14COM2            LCDDATA7bits.SEG14COM2         /* bit 6 */
#define SEG15COM2            LCDDATA7bits.SEG15COM2         /* bit 7 */

#define SEG16COM2            LCDDATA8bits.SEG16COM2         /* bit 0 */
#define SEG17COM2            LCDDATA8bits.SEG17COM2         /* bit 1 */
#define SEG18COM2            LCDDATA8bits.SEG18COM2         /* bit 2 */
#define SEG19COM2            LCDDATA8bits.SEG19COM2         /* bit 3 */
#define SEG20COM2            LCDDATA8bits.SEG20COM2         /* bit 4 */
#define SEG21COM2            LCDDATA8bits.SEG21COM2         /* bit 5 */
#define SEG22COM2            LCDDATA8bits.SEG22COM2         /* bit 6 */
#define SEG23COM2            LCDDATA8bits.SEG23COM2         /* bit 7 */

#define SEG0COM3             LCDDATA9bits.SEG0COM3          /* bit 0 */
#define SEG1COM3             LCDDATA9bits.SEG1COM3          /* bit 1 */
#define SEG2COM3             LCDDATA9bits.SEG2COM3          /* bit 2 */
#define SEG3COM3             LCDDATA9bits.SEG3COM3          /* bit 3 */
#define SEG4COM3             LCDDATA9bits.SEG4COM3          /* bit 4 */
#define SEG5COM3             LCDDATA9bits.SEG5COM3          /* bit 5 */
#define SEG6COM3             LCDDATA9bits.SEG6COM3          /* bit 6 */
#define SEG7COM3             LCDDATA9bits.SEG7COM3          /* bit 7 */

#define LP0                  LCDPSbits.LP0                  /* bit 0 */
#define LP1                  LCDPSbits.LP1                  /* bit 1 */
#define LP2                  LCDPSbits.LP2                  /* bit 2 */
#define LP3                  LCDPSbits.LP3                  /* bit 3 */
#define WA                   LCDPSbits.WA                   /* bit 4 */
#define LCDA                 LCDPSbits.LCDA                 /* bit 5 */
#define BIASMD               LCDPSbits.BIASMD               /* bit 6 */
#define WFT                  LCDPSbits.WFT                  /* bit 7 */

#define VLCD1PE              LCDREFbits.VLCD1PE             /* bit 1 */
#define VLCD2PE              LCDREFbits.VLCD2PE             /* bit 2 */
#define VLCD3PE              LCDREFbits.VLCD3PE             /* bit 3 */
#define LCDIRI               LCDREFbits.LCDIRI              /* bit 5 */
#define LCDIRE               LCDREFbits.LCDIRE              /* bit 7 */

#define LRLAT0               LCDRLbits.LRLAT0               /* bit 0 */
#define LRLAT1               LCDRLbits.LRLAT1               /* bit 1 */
#define LRLAT2               LCDRLbits.LRLAT2               /* bit 2 */
#define LRLBP0               LCDRLbits.LRLBP0               /* bit 4 */
#define LRLBP1               LCDRLbits.LRLBP1               /* bit 5 */
#define LRLAP0               LCDRLbits.LRLAP0               /* bit 6 */
#define LRLAP1               LCDRLbits.LRLAP1               /* bit 7 */

#define SE0                  LCDSE0bits.SE0                 /* bit 0 */
#define SE1                  LCDSE0bits.SE1                 /* bit 1 */
#define SE2                  LCDSE0bits.SE2                 /* bit 2 */
#define SE3                  LCDSE0bits.SE3                 /* bit 3 */
#define SE4                  LCDSE0bits.SE4                 /* bit 4 */
#define SE5                  LCDSE0bits.SE5                 /* bit 5 */
#define SE6                  LCDSE0bits.SE6                 /* bit 6 */
#define SE7                  LCDSE0bits.SE7                 /* bit 7 */

#define SE8                  LCDSE1bits.SE8                 /* bit 0 */
#define SE9                  LCDSE1bits.SE9                 /* bit 1 */
#define SE10                 LCDSE1bits.SE10                /* bit 2 */
#define SE11                 LCDSE1bits.SE11                /* bit 3 */
#define SE12                 LCDSE1bits.SE12                /* bit 4 */
#define SE13                 LCDSE1bits.SE13                /* bit 5 */
#define SE14                 LCDSE1bits.SE14                /* bit 6 */
#define SE15                 LCDSE1bits.SE15                /* bit 7 */

#define SE16                 LCDSE2bits.SE16                /* bit 0 */
#define SE24                 LCDSE2bits.SE24                /* bit 0 */
#define SE17                 LCDSE2bits.SE17                /* bit 1 */
#define SE25                 LCDSE2bits.SE25                /* bit 1 */
#define SE18                 LCDSE2bits.SE18                /* bit 2 */
#define SE26                 LCDSE2bits.SE26                /* bit 2 */
#define SE19                 LCDSE2bits.SE19                /* bit 3 */
#define SE27                 LCDSE2bits.SE27                /* bit 3 */
#define SE20                 LCDSE2bits.SE20                /* bit 4 */
#define SE28                 LCDSE2bits.SE28                /* bit 4 */
#define SE21                 LCDSE2bits.SE21                /* bit 5 */
#define SE22                 LCDSE2bits.SE22                /* bit 6 */
#define SE23                 LCDSE2bits.SE23                /* bit 7 */

#define PS0                  OPTION_REGbits.PS0             /* bit 0 */
#define PS1                  OPTION_REGbits.PS1             /* bit 1 */
#define PS2                  OPTION_REGbits.PS2             /* bit 2 */
#define PSA                  OPTION_REGbits.PSA             /* bit 3 */
#define T0SE                 OPTION_REGbits.T0SE            /* bit 4 */
#define TMR0SE               OPTION_REGbits.TMR0SE          /* bit 4 */
#define T0CS                 OPTION_REGbits.T0CS            /* bit 5 */
#define TMR0CS               OPTION_REGbits.TMR0CS          /* bit 5 */
#define INTEDG               OPTION_REGbits.INTEDG          /* bit 6 */
#define NOT_WPUEN            OPTION_REGbits.NOT_WPUEN       /* bit 7 */

#define SCS0                 OSCCONbits.SCS0                /* bit 0 */
#define SCS1                 OSCCONbits.SCS1                /* bit 1 */
#define IRCF0                OSCCONbits.IRCF0               /* bit 3 */
#define IRCF1                OSCCONbits.IRCF1               /* bit 4 */
#define IRCF2                OSCCONbits.IRCF2               /* bit 5 */
#define IRCF3                OSCCONbits.IRCF3               /* bit 6 */

#define HFIOFS               OSCSTATbits.HFIOFS             /* bit 0 */
#define LFIOFR               OSCSTATbits.LFIOFR             /* bit 1 */
#define HFIOFR               OSCSTATbits.HFIOFR             /* bit 4 */
#define OSTS                 OSCSTATbits.OSTS               /* bit 5 */
#define T1OSCR               OSCSTATbits.T1OSCR             /* bit 7 */

#define NOT_BOR              PCONbits.NOT_BOR               /* bit 0 */
#define NOT_POR              PCONbits.NOT_POR               /* bit 1 */
#define NOT_RI               PCONbits.NOT_RI                /* bit 2 */
#define NOT_RMCLR            PCONbits.NOT_RMCLR             /* bit 3 */
#define NOT_RWDT             PCONbits.NOT_RWDT              /* bit 4 */
#define STKUNF               PCONbits.STKUNF                /* bit 6 */
#define STKOVF               PCONbits.STKOVF                /* bit 7 */

#define TMR1IE               PIE1bits.TMR1IE                /* bit 0 */
#define TXIE                 PIE1bits.TXIE                  /* bit 4 */
#define RCIE                 PIE1bits.RCIE                  /* bit 5 */
#define ADIE                 PIE1bits.ADIE                  /* bit 6 */
#define TMR1GIE              PIE1bits.TMR1GIE               /* bit 7 */

#define LCDIE                PIE2bits.LCDIE                 /* bit 2 */

#define TMR1IF               PIR1bits.TMR1IF                /* bit 0 */
#define TXIF                 PIR1bits.TXIF                  /* bit 4 */
#define RCIF                 PIR1bits.RCIF                  /* bit 5 */
#define ADIF                 PIR1bits.ADIF                  /* bit 6 */
#define TMR1GIF              PIR1bits.TMR1GIF               /* bit 7 */

#define LCDIF                PIR2bits.LCDIF                 /* bit 2 */

#define RD                   PMCON1bits.RD                  /* bit 0 */
#define WR                   PMCON1bits.WR                  /* bit 1 */
#define WREN                 PMCON1bits.WREN                /* bit 2 */
#define WRERR                PMCON1bits.WRERR               /* bit 3 */
#define FREE                 PMCON1bits.FREE                /* bit 4 */
#define LWLO                 PMCON1bits.LWLO                /* bit 5 */
#define CFGS                 PMCON1bits.CFGS                /* bit 6 */

#define RA0                  PORTAbits.RA0                  /* bit 0 */
#define RA1                  PORTAbits.RA1                  /* bit 1 */
#define RA2                  PORTAbits.RA2                  /* bit 2 */
#define RA3                  PORTAbits.RA3                  /* bit 3 */
#define RA4                  PORTAbits.RA4                  /* bit 4 */
#define RA5                  PORTAbits.RA5                  /* bit 5 */
#define RA6                  PORTAbits.RA6                  /* bit 6 */
#define RA7                  PORTAbits.RA7                  /* bit 7 */

#define RB0                  PORTBbits.RB0                  /* bit 0 */
#define RB1                  PORTBbits.RB1                  /* bit 1 */
#define RB2                  PORTBbits.RB2                  /* bit 2 */
#define RB3                  PORTBbits.RB3                  /* bit 3 */
#define RB4                  PORTBbits.RB4                  /* bit 4 */
#define RB5                  PORTBbits.RB5                  /* bit 5 */
#define RB6                  PORTBbits.RB6                  /* bit 6 */
#define RB7                  PORTBbits.RB7                  /* bit 7 */

#define RC0                  PORTCbits.RC0                  /* bit 0 */
#define RC1                  PORTCbits.RC1                  /* bit 1 */
#define RC2                  PORTCbits.RC2                  /* bit 2 */
#define RC3                  PORTCbits.RC3                  /* bit 3 */
#define RC4                  PORTCbits.RC4                  /* bit 4 */
#define RC5                  PORTCbits.RC5                  /* bit 5 */
#define RC6                  PORTCbits.RC6                  /* bit 6 */
#define RC7                  PORTCbits.RC7                  /* bit 7 */

#define RD0                  PORTDbits.RD0                  /* bit 0 */
#define RD1                  PORTDbits.RD1                  /* bit 1 */
#define RD2                  PORTDbits.RD2                  /* bit 2 */
#define RD3                  PORTDbits.RD3                  /* bit 3 */
#define RD4                  PORTDbits.RD4                  /* bit 4 */
#define RD5                  PORTDbits.RD5                  /* bit 5 */
#define RD6                  PORTDbits.RD6                  /* bit 6 */
#define RD7                  PORTDbits.RD7                  /* bit 7 */

#define RE0                  PORTEbits.RE0                  /* bit 0 */
#define RE1                  PORTEbits.RE1                  /* bit 1 */
#define RE2                  PORTEbits.RE2                  /* bit 2 */
#define RE3                  PORTEbits.RE3                  /* bit 3 */

#define RX9D                 RC1STAbits.RX9D                /* bit 0, shadows bit in RCSTAbits, RCSTA1bits */
#define OERR                 RC1STAbits.OERR                /* bit 1, shadows bit in RCSTAbits, RCSTA1bits */
#define FERR                 RC1STAbits.FERR                /* bit 2, shadows bit in RCSTAbits, RCSTA1bits */
#define ADDEN                RC1STAbits.ADDEN               /* bit 3, shadows bit in RCSTAbits, RCSTA1bits */
#define CREN                 RC1STAbits.CREN                /* bit 4, shadows bit in RCSTAbits, RCSTA1bits */
#define SREN                 RC1STAbits.SREN                /* bit 5, shadows bit in RCSTAbits, RCSTA1bits */
#define RX9                  RC1STAbits.RX9                 /* bit 6, shadows bit in RCSTAbits, RCSTA1bits */
#define SPEN                 RC1STAbits.SPEN                /* bit 7, shadows bit in RCSTAbits, RCSTA1bits */

#define BRG8                 SP1BRGHbits.BRG8               /* bit 0, shadows bit in SPBRGHbits, SPBRGH1bits */
#define BRG9                 SP1BRGHbits.BRG9               /* bit 1, shadows bit in SPBRGHbits, SPBRGH1bits */
#define BRG10                SP1BRGHbits.BRG10              /* bit 2, shadows bit in SPBRGHbits, SPBRGH1bits */
#define BRG11                SP1BRGHbits.BRG11              /* bit 3, shadows bit in SPBRGHbits, SPBRGH1bits */
#define BRG12                SP1BRGHbits.BRG12              /* bit 4, shadows bit in SPBRGHbits, SPBRGH1bits */
#define BRG13                SP1BRGHbits.BRG13              /* bit 5, shadows bit in SPBRGHbits, SPBRGH1bits */
#define BRG14                SP1BRGHbits.BRG14              /* bit 6, shadows bit in SPBRGHbits, SPBRGH1bits */
#define BRG15                SP1BRGHbits.BRG15              /* bit 7, shadows bit in SPBRGHbits, SPBRGH1bits */

#define BRG0                 SP1BRGLbits.BRG0               /* bit 0, shadows bit in SPBRGbits, SPBRGLbits, SPBRGL1bits */
#define BRG1                 SP1BRGLbits.BRG1               /* bit 1, shadows bit in SPBRGbits, SPBRGLbits, SPBRGL1bits */
#define BRG2                 SP1BRGLbits.BRG2               /* bit 2, shadows bit in SPBRGbits, SPBRGLbits, SPBRGL1bits */
#define BRG3                 SP1BRGLbits.BRG3               /* bit 3, shadows bit in SPBRGbits, SPBRGLbits, SPBRGL1bits */
#define BRG4                 SP1BRGLbits.BRG4               /* bit 4, shadows bit in SPBRGbits, SPBRGLbits, SPBRGL1bits */
#define BRG5                 SP1BRGLbits.BRG5               /* bit 5, shadows bit in SPBRGbits, SPBRGLbits, SPBRGL1bits */
#define BRG6                 SP1BRGLbits.BRG6               /* bit 6, shadows bit in SPBRGbits, SPBRGLbits, SPBRGL1bits */
#define BRG7                 SP1BRGLbits.BRG7               /* bit 7, shadows bit in SPBRGbits, SPBRGLbits, SPBRGL1bits */

#define C_SHAD               STATUS_SHADbits.C_SHAD         /* bit 0 */
#define DC_SHAD              STATUS_SHADbits.DC_SHAD        /* bit 1 */
#define Z_SHAD               STATUS_SHADbits.Z_SHAD         /* bit 2 */

#define C                    STATUSbits.C                   /* bit 0 */
#define DC                   STATUSbits.DC                  /* bit 1 */
#define Z                    STATUSbits.Z                   /* bit 2 */
#define NOT_PD               STATUSbits.NOT_PD              /* bit 3 */
#define NOT_TO               STATUSbits.NOT_TO              /* bit 4 */

#define TMR1ON               T1CONbits.TMR1ON               /* bit 0 */
#define NOT_T1SYNC           T1CONbits.NOT_T1SYNC           /* bit 2 */
#define T1OSCEN              T1CONbits.T1OSCEN              /* bit 3 */
#define T1CKPS0              T1CONbits.T1CKPS0              /* bit 4 */
#define T1CKPS1              T1CONbits.T1CKPS1              /* bit 5 */
#define TMR1CS0              T1CONbits.TMR1CS0              /* bit 6 */
#define TMR1CS1              T1CONbits.TMR1CS1              /* bit 7 */

#define T1GSS0               T1GCONbits.T1GSS0              /* bit 0 */
#define T1GSS1               T1GCONbits.T1GSS1              /* bit 1 */
#define T1GVAL               T1GCONbits.T1GVAL              /* bit 2 */
#define T1GGO                T1GCONbits.T1GGO               /* bit 3 */
#define T1GGO_NOT_DONE       T1GCONbits.T1GGO_NOT_DONE      /* bit 3 */
#define T1GSPM               T1GCONbits.T1GSPM              /* bit 4 */
#define T1GTM                T1GCONbits.T1GTM               /* bit 5 */
#define T1GPOL               T1GCONbits.T1GPOL              /* bit 6 */
#define TMR1GE               T1GCONbits.TMR1GE              /* bit 7 */

#define TRISA0               TRISAbits.TRISA0               /* bit 0 */
#define TRISA1               TRISAbits.TRISA1               /* bit 1 */
#define TRISA2               TRISAbits.TRISA2               /* bit 2 */
#define TRISA3               TRISAbits.TRISA3               /* bit 3 */
#define TRISA4               TRISAbits.TRISA4               /* bit 4 */
#define TRISA5               TRISAbits.TRISA5               /* bit 5 */
#define TRISA6               TRISAbits.TRISA6               /* bit 6 */
#define TRISA7               TRISAbits.TRISA7               /* bit 7 */

#define TRISB0               TRISBbits.TRISB0               /* bit 0 */
#define TRISB1               TRISBbits.TRISB1               /* bit 1 */
#define TRISB2               TRISBbits.TRISB2               /* bit 2 */
#define TRISB3               TRISBbits.TRISB3               /* bit 3 */
#define TRISB4               TRISBbits.TRISB4               /* bit 4 */
#define TRISB5               TRISBbits.TRISB5               /* bit 5 */
#define TRISB6               TRISBbits.TRISB6               /* bit 6 */
#define TRISB7               TRISBbits.TRISB7               /* bit 7 */

#define TRISC0               TRISCbits.TRISC0               /* bit 0 */
#define TRISC1               TRISCbits.TRISC1               /* bit 1 */
#define TRISC2               TRISCbits.TRISC2               /* bit 2 */
#define TRISC3               TRISCbits.TRISC3               /* bit 3 */
#define TRISC4               TRISCbits.TRISC4               /* bit 4 */
#define TRISC5               TRISCbits.TRISC5               /* bit 5 */
#define TRISC6               TRISCbits.TRISC6               /* bit 6 */
#define TRISC7               TRISCbits.TRISC7               /* bit 7 */

#define TRISD0               TRISDbits.TRISD0               /* bit 0 */
#define TRISD1               TRISDbits.TRISD1               /* bit 1 */
#define TRISD2               TRISDbits.TRISD2               /* bit 2 */
#define TRISD3               TRISDbits.TRISD3               /* bit 3 */
#define TRISD4               TRISDbits.TRISD4               /* bit 4 */
#define TRISD5               TRISDbits.TRISD5               /* bit 5 */
#define TRISD6               TRISDbits.TRISD6               /* bit 6 */
#define TRISD7               TRISDbits.TRISD7               /* bit 7 */

#define TRISE0               TRISEbits.TRISE0               /* bit 0 */
#define TRISE1               TRISEbits.TRISE1               /* bit 1 */
#define TRISE2               TRISEbits.TRISE2               /* bit 2 */

#define TX9D                 TX1STAbits.TX9D                /* bit 0, shadows bit in TXSTAbits, TXSTA1bits */
#define TRMT                 TX1STAbits.TRMT                /* bit 1, shadows bit in TXSTAbits, TXSTA1bits */
#define BRGH                 TX1STAbits.BRGH                /* bit 2, shadows bit in TXSTAbits, TXSTA1bits */
#define SENDB                TX1STAbits.SENDB               /* bit 3, shadows bit in TXSTAbits, TXSTA1bits */
#define SYNC                 TX1STAbits.SYNC                /* bit 4, shadows bit in TXSTAbits, TXSTA1bits */
#define TXEN                 TX1STAbits.TXEN                /* bit 5, shadows bit in TXSTAbits, TXSTA1bits */
#define TX9                  TX1STAbits.TX9                 /* bit 6, shadows bit in TXSTAbits, TXSTA1bits */
#define CSRC                 TX1STAbits.CSRC                /* bit 7, shadows bit in TXSTAbits, TXSTA1bits */

#define SWDTEN               WDTCONbits.SWDTEN              /* bit 0 */
#define WDTPS0               WDTCONbits.WDTPS0              /* bit 1 */
#define WDTPS1               WDTCONbits.WDTPS1              /* bit 2 */
#define WDTPS2               WDTCONbits.WDTPS2              /* bit 3 */
#define WDTPS3               WDTCONbits.WDTPS3              /* bit 4 */
#define WDTPS4               WDTCONbits.WDTPS4              /* bit 5 */

#define WPUB0                WPUBbits.WPUB0                 /* bit 0 */
#define WPUB1                WPUBbits.WPUB1                 /* bit 1 */
#define WPUB2                WPUBbits.WPUB2                 /* bit 2 */
#define WPUB3                WPUBbits.WPUB3                 /* bit 3 */
#define WPUB4                WPUBbits.WPUB4                 /* bit 4 */
#define WPUB5                WPUBbits.WPUB5                 /* bit 5 */
#define WPUB6                WPUBbits.WPUB6                 /* bit 6 */
#define WPUB7                WPUBbits.WPUB7                 /* bit 7 */

#define WPUE3                WPUEbits.WPUE3                 /* bit 3 */
#endif /* NO_BIT_DEFINES */

#endif
