include ../build.mk
include $(SETUP_BUILD)
#
# misc test rom
include $(CONFIG_ROM)

LOCAL_RES_DIR := ./res
include $(BUILD_RESOURCES)

LOCAL_ROM_NAME := isometric_test
LOCAL_SRC_FILES := isometric_test.c
include $(BUILD_ROM_32K)
