include ../build.mk
include $(SETUP_BUILD)
#
# hello msx rom
include $(CONFIG_ROM)

LOCAL_RES_DIR := ./res
include $(BUILD_RESOURCES)

LOCAL_ROM_NAME := sheeep
LOCAL_SRC_FILES := sheeep.c
include $(BUILD_ROM_32K)
